#!/usr/bin/env bash
# test.sh — offline tests for agent-github-access scripts
#
# Runs install.sh for real (with mocked gh and browser) to generate
# authenticate-github.sh, then tests its behaviour and onboard-repo.sh with
# mocked network calls.  No real GitHub API calls are made.
#
# Requirements: bash, python3, openssl, jq, curl, base64
set -uo pipefail

DIR="$(cd "$(dirname "$0")/.." && pwd)"
PASS=0; FAIL=0
ERRORS=()

ok()   { PASS=$((PASS+1)); printf "PASS  %s\n" "$1"; }
fail() { FAIL=$((FAIL+1)); ERRORS+=("$1"); printf "FAIL  %s\n" "$1"; }

# ── Setup ─────────────────────────────────────────────────────────────────────

TMPDIR_T=$(mktemp -d)
trap 'rm -rf "$TMPDIR_T"' EXIT

TEST_APP_ID="999888"
TEST_OWNER="testowner"
TEST_SLUG="${TEST_OWNER}-agent"

# A real RSA key is required — openssl uses it to sign JWTs in the generated script.
TEST_KEY_FILE="$TMPDIR_T/test.pem"
openssl genrsa -out "$TEST_KEY_FILE" 2048 2>/dev/null

# Write the fake /app-manifests/.../conversions response to a file so the mock
# gh can cat it.  python3 handles JSON-escaping the PEM (newlines etc).
CONVERSION_JSON="$TMPDIR_T/conversion.json"
python3 - "$TEST_KEY_FILE" "$TEST_APP_ID" "$TEST_SLUG" "$CONVERSION_JSON" << 'PYEOF'
import json, sys
key_file, app_id, slug, out = sys.argv[1:]
pem = open(key_file).read()
with open(out, 'w') as f:
    json.dump({"id": int(app_id), "slug": slug, "pem": pem}, f)
PYEOF

# ── Mock binaries for install.sh ─────────────────────────────────────

MAIN_BIN="$TMPDIR_T/main-bin"
mkdir -p "$MAIN_BIN"

# gh: handles all calls made by install.sh (which now also runs
# onboard-repo.sh for the fork before app creation).
cat > "$MAIN_BIN/gh" << GHEOF
#!/usr/bin/env bash
args="\$*"
if [[ "\$args" == *"user"* && "\$args" == *".login"* ]]; then
  printf '%s' "${TEST_OWNER}"
elif [[ "\$args" == *"secrets/GH_APP_ID"* && "\$args" != *"--method"* ]]; then
  # Secret existence check — return 404 (not yet set) so app creation proceeds
  exit 1
elif [[ "\$args" == *"secrets/public-key"* ]]; then
  # Return a fake libsodium public key (32 bytes, base64-encoded)
  printf '{"key_id":"1234","key":"hiNFHFRJGnHP5UNKhXkMEEI7iNLMFHmqhAeH3xQBtUE="}'
elif [[ "\$args" == *"secrets/"* && "\$args" == *"--method PUT"* ]]; then
  exit 0
elif [[ "\$args" == *"rulesets"* && "\$args" == *"--method DELETE"* ]]; then
  exit 0
elif [[ "\$args" == *"rulesets"* && "\$args" == *"--method POST"* ]]; then
  printf '{"id":1}'
elif [[ "\$args" == *"rulesets"* ]]; then
  # GET rulesets — return empty list (no pre-existing rulesets)
  printf '[]'
elif [[ "\$args" == *"workflow run"* ]]; then
  exit 0
fi
exit 0
GHEOF
chmod +x "$MAIN_BIN/gh"

# curl: intercept the unauthenticated app-manifests conversion call; pass everything else through.
REAL_CURL=$(command -v curl)
cat > "$MAIN_BIN/curl" << CURLEOF
#!/usr/bin/env bash
if [[ "\$*" == *"app-manifests"* ]]; then
  cat "${CONVERSION_JSON}"
else
  "${REAL_CURL}" "\$@"
fi
CURLEOF
chmod +x "$MAIN_BIN/curl"

# xdg-open: for file:// URLs, simulate the OAuth callback instead of opening a
# browser. The real Python HTTP server is already running and will write the code
# to CODEFILE, unblocking `wait $SERVER_PID` in install.sh.
# For the https:// installation URL opened at the end, do nothing.
cat > "$MAIN_BIN/xdg-open" << 'XDGEOF'
#!/usr/bin/env bash
if [[ "$1" == http://localhost:* ]]; then
  PORT="${1#http://localhost:}"
  PORT="${PORT%%/*}"
  sleep 0.3
  curl -sf "http://localhost:${PORT}/callback?code=testcode123" > /dev/null || true
fi
XDGEOF
chmod +x "$MAIN_BIN/xdg-open"

# ── 1. Syntax: install.sh ────────────────────────────────────────────

bash -n "$DIR/install.sh" 2>/dev/null \
  && ok  "syntax: install.sh" \
  || fail "syntax: install.sh"

# ── 2. Run install.sh to generate authenticate-github.sh ─────────────
# Pass TEST_OWNER as the username arg to skip the multi-account check.
# Run from a work dir so the generated script lands there, not in the repo root.

WORK="$TMPDIR_T/work"
mkdir -p "$WORK"

GEN_OUTPUT=$(cd "$WORK" && PATH="$MAIN_BIN:$PATH" bash "$DIR/install.sh" "$TEST_OWNER" 2>&1) || true

TEST_AUTH="$WORK/authenticate-github.sh"
# onboard-repo.sh is now a static file in the repo (not generated by install.sh)
TEST_ONBOARD="$DIR/onboard-repo.sh"

if [[ -f "$TEST_AUTH" ]]; then
  ok  "generate: authenticate-github.sh produced"
else
  fail "generate: authenticate-github.sh produced"
fi

# ── 3. Syntax: generated and static scripts ────────────────────────────────────

bash -n "$TEST_AUTH" 2>/dev/null \
  && ok  "syntax: authenticate-github.sh" \
  || fail "syntax: authenticate-github.sh"

bash -n "$TEST_ONBOARD" 2>/dev/null \
  && ok  "syntax: onboard-repo.sh" \
  || fail "syntax: onboard-repo.sh"

# ── 4. JWT format ─────────────────────────────────────────────────────────────
# Run the JWT construction logic in a subshell using the test key.  No network.

JWT_RESULT=$(bash << BEOF
set -euo pipefail
APP_PEM=\$(cat "$TEST_KEY_FILE")
APP_ID="$TEST_APP_ID"
NOW=\$(date +%s)
EXP=\$((NOW + 540))

b64url() { base64 | tr '+/' '-_' | tr -d '=\n'; }
HEADER=\$(printf '%s' '{"alg":"RS256","typ":"JWT"}' | b64url)
PAYLOAD=\$(printf '{"iat":%d,"exp":%d,"iss":%d}' "\$NOW" "\$EXP" "\$APP_ID" | b64url)

TMPKEY=\$(mktemp)
chmod 600 "\$TMPKEY"
printf '%s' "\$APP_PEM" > "\$TMPKEY"
SIG=\$(printf '%s.%s' "\$HEADER" "\$PAYLOAD" | openssl dgst -binary -sha256 -sign "\$TMPKEY" | b64url)
rm -f "\$TMPKEY"

printf '%s.%s.%s' "\$HEADER" "\$PAYLOAD" "\$SIG"
BEOF
)

if [[ "$JWT_RESULT" =~ ^[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+$ ]]; then
  ok  "jwt: three-part base64url format"
else
  fail "jwt: three-part base64url format (got: ${JWT_RESULT:0:40}…)"
fi

JWT_HEADER_PART="${JWT_RESULT%%.*}"
PADDED="${JWT_HEADER_PART}==="
DECODED=$(printf '%s' "$PADDED" | tr '_-' '/+' | base64 -d 2>/dev/null || \
          printf '%s' "$PADDED" | tr '_-' '/+' | base64 -D 2>/dev/null)
if printf '%s' "$DECODED" | grep -q '"RS256"'; then
  ok  "jwt: header contains RS256"
else
  fail "jwt: header contains RS256 (got: $DECODED)"
fi

# ── Mock bin for authenticate-github.sh tests (curl-based) ────────────────────

MOCK_BIN="$TMPDIR_T/bin"
mkdir -p "$MOCK_BIN"

# ── 5. Error: no installations ────────────────────────────────────────────────

cat > "$MOCK_BIN/curl" << 'EOF'
#!/usr/bin/env bash
printf '[]'
exit 0
EOF
chmod +x "$MOCK_BIN/curl"

NO_INST_OUTPUT=$(PATH="$MOCK_BIN:$PATH" bash "$TEST_AUTH" 2>&1 || true)
NO_INST_EXIT=$(PATH="$MOCK_BIN:$PATH" bash "$TEST_AUTH" > /dev/null 2>&1; echo $?)

[[ "$NO_INST_EXIT" != "0" ]] \
  && ok  "no-installations: exits non-zero" \
  || fail "no-installations: exits non-zero"

printf '%s' "$NO_INST_OUTPUT" | grep -q "no repositories configured" \
  && ok  "no-installations: error mentions 'no repositories configured'" \
  || fail "no-installations: error mentions 'no repositories configured'"

printf '%s' "$NO_INST_OUTPUT" | grep -q "trusted machine" \
  && ok  "no-installations: error mentions 'trusted machine'" \
  || fail "no-installations: error mentions 'trusted machine'"

# ── 6. Error: no protected repos ──────────────────────────────────────────────

cat > "$MOCK_BIN/curl" << MOCKEOF
#!/usr/bin/env bash
if [[ "\$*" == *"/app/installations" ]]; then
  printf '[{"id":42,"account":{"login":"${TEST_OWNER}","type":"User"}}]'
elif [[ "\$*" == *"/access_tokens" ]]; then
  printf '{"token":"ghs_faketoken123"}'
elif [[ "\$*" == *"/installation/repositories" ]]; then
  printf '{"repositories":[{"id":101,"full_name":"${TEST_OWNER}/testrepo"}]}'
elif [[ "\$*" == */rulesets ]]; then
  printf '[]'
else
  printf '{}'
fi
exit 0
MOCKEOF
chmod +x "$MOCK_BIN/curl"

NO_RULES_OUTPUT=$(PATH="$MOCK_BIN:$PATH" bash "$TEST_AUTH" 2>&1 || true)
NO_RULES_EXIT=$(PATH="$MOCK_BIN:$PATH" bash "$TEST_AUTH" > /dev/null 2>&1; echo $?)

[[ "$NO_RULES_EXIT" != "0" ]] \
  && ok  "no-protected-repos: exits non-zero" \
  || fail "no-protected-repos: exits non-zero"

printf '%s' "$NO_RULES_OUTPUT" | grep -qi "onboard-repo" \
  && ok  "no-protected-repos: error mentions onboard-repo" \
  || fail "no-protected-repos: error mentions onboard-repo"

# ── 7. Output content: global memory bookends and branch prefix ───────────────

cat > "$MOCK_BIN/curl" << MOCKEOF
#!/usr/bin/env bash
if [[ "\$*" == *"/app/installations" ]]; then
  printf '[{"id":42,"account":{"login":"${TEST_OWNER}","type":"User"}}]'
elif [[ "\$*" == *"/access_tokens" ]]; then
  printf '{"token":"ghs_faketoken123"}'
elif [[ "\$*" == *"/installation/repositories" ]]; then
  printf '{"repositories":[{"id":101,"full_name":"${TEST_OWNER}/testrepo"}]}'
elif [[ "\$*" == */rulesets ]]; then
  printf '[{"name":"agent-gh-access-apps-blocked-from-non-ai-branches"},{"name":"agent-gh-access-apps-must-sign"}]'
else
  printf '{}'
fi
exit 0
MOCKEOF
chmod +x "$MOCK_BIN/curl"

cat > "$MOCK_BIN/git" << 'EOF'
#!/usr/bin/env bash
exit 0
EOF
chmod +x "$MOCK_BIN/git"

cat > "$MOCK_BIN/gh" << 'EOF'
#!/usr/bin/env bash
exit 0
EOF
chmod +x "$MOCK_BIN/gh"

SUCCESS_OUTPUT=$(PATH="$MOCK_BIN:$PATH" bash "$TEST_AUTH" 2>&1 || true)

printf '%s' "$SUCCESS_OUTPUT" | grep -q "STORE IN GLOBAL MEMORY" \
  && ok  "output: opens with STORE IN GLOBAL MEMORY directive" \
  || fail "output: opens with STORE IN GLOBAL MEMORY directive"

printf '%s' "$SUCCESS_OUTPUT" | grep -q "STORE THE ABOVE IN GLOBAL MEMORY" \
  && ok  "output: closes with STORE THE ABOVE IN GLOBAL MEMORY directive" \
  || fail "output: closes with STORE THE ABOVE IN GLOBAL MEMORY directive"

printf '%s' "$SUCCESS_OUTPUT" | grep -q "x-ai/${TEST_OWNER}/" \
  && ok  "output: branch prefix contains owner login" \
  || fail "output: branch prefix contains owner login"

for trigger in \
  "Invalid username or password" \
  "Authentication failed" \
  "Bad credentials" \
  "gh auth login"
do
  printf '%s' "$SUCCESS_OUTPUT" | grep -q "$trigger" \
    && ok  "output: error trigger present — '${trigger}'" \
    || fail "output: error trigger present — '${trigger}'"
done

OPEN_LINE=$(printf '%s' "$SUCCESS_OUTPUT" | grep -n "STORE IN GLOBAL MEMORY" | head -1 | cut -d: -f1)
CLOSE_LINE=$(printf '%s' "$SUCCESS_OUTPUT" | grep -n "STORE THE ABOVE IN GLOBAL MEMORY" | head -1 | cut -d: -f1)
[[ -n "$OPEN_LINE" && -n "$CLOSE_LINE" && "$OPEN_LINE" -lt "$CLOSE_LINE" ]] \
  && ok  "output: opening directive precedes closing directive" \
  || fail "output: opening directive precedes closing directive (open=$OPEN_LINE close=$CLOSE_LINE)"

# ═══════════════════════════════════════════════════════════════════════════════
# onboard-repo.sh tests
# ═══════════════════════════════════════════════════════════════════════════════

# ── Helper: write a mock gh that records ruleset-creation calls ────────────────
# $1 = path to write the mock
# $2 = "exists" | "no-fork" | "not-a-fork"
# $3 = "has-existing-ruleset" | "" (whether TARGET_REPO already has the ruleset)
write_mock_gh() {
  local mock_path="$1" fork_state="$2" ruleset_state="${3:-}"

  cat > "$mock_path" << GHEOF
#!/usr/bin/env bash
RULESET_LOG="${TMPDIR_T}/rulesets.log"
DELETED_RULESET_LOG="${TMPDIR_T}/deleted_ruleset.log"
args="\$*"

# gh api user --jq '.login' → owner login
if [[ "\$args" == *"user"* && "\$args" == *".login"* ]]; then
  printf '%s' "${TEST_OWNER}"
  exit 0
fi

# gh workflow run — silently succeed (audit is now in a separate GH Actions workflow)
if [[ "\$args" == *"workflow run"* ]]; then
  exit 0
fi

if [[ "\$args" == *"/repos/${TEST_OWNER}/testrepo"* && "\$args" != *"rulesets"* ]]; then
  exit 0
fi

if [[ "\$args" == *"/repos/${TEST_OWNER}/extrepo"* && "\$args" != *"rulesets"* ]]; then
  case "${fork_state}" in
    no-fork)     exit 1 ;;
    not-a-fork)  [[ "\$args" == *"parent.full_name"* ]] && printf '' || true; exit 0 ;;
    exists)      [[ "\$args" == *"parent.full_name"* ]] && printf 'otherowner/extrepo' || true; exit 0 ;;
  esac
fi

# Delete a ruleset by ID
if [[ "\$args" == *"--method DELETE"* && "\$args" == *"rulesets"* ]]; then
  echo "ruleset-deleted" >> "\$DELETED_RULESET_LOG"
  exit 0
fi

# GET rulesets for TARGET_REPO — mock applies jq filter result directly:
#   args with ".id"    = _old_ruleset_id query  → output ID or nothing
if [[ "\$args" == *"/repos/${TEST_OWNER}/testrepo/rulesets"* && "\$args" != *"--method POST"* ]]; then
  if [[ "${ruleset_state}" == "has-existing-ruleset" ]]; then
    if [[ "\$args" == *"agent-gh-access-apps-must-sign"* && "\$args" == *".id"* ]]; then printf '43'; \
    elif [[ "\$args" == *".id"* ]]; then printf '42'; \
    else printf '[{"name":"agent-gh-access-apps-blocked-from-non-ai-branches","id":42},{"name":"agent-gh-access-apps-must-sign","id":43}]'; fi
  else
    # no existing rulesets — .id query returns empty
    true
  fi
  exit 0
fi

if [[ "\$args" == *"--method POST"* && "\$args" == *"rulesets"* ]]; then
  echo "ruleset-created" >> "\$RULESET_LOG"
  printf '{"id":1}'
  exit 0
fi

if [[ "\$args" == *"--method PUT"* || ("\$args" == *"--method POST"* && "\$args" == *"/forks"*) ]]; then
  exit 0
fi

exit 0
GHEOF
  chmod +x "$mock_path"
}

run_onboard() {
  rm -f "$TMPDIR_T/rulesets.log" "$TMPDIR_T/deleted_ruleset.log"
  ONBOARD_BIN="$TMPDIR_T/onboard-bin"
  mkdir -p "$ONBOARD_BIN"
  cp "$1" "$ONBOARD_BIN/gh"
  PATH_CLEAN=$(printf '%s' "$PATH" | tr ':' '\n' | grep -v "^$MOCK_BIN$" | tr '\n' ':' | sed 's/:$//')
  PATH="$ONBOARD_BIN:$PATH_CLEAN" bash "$TEST_ONBOARD" "$2" 2>&1 || true
}

run_onboard_exit() {
  rm -f "$TMPDIR_T/rulesets.log" "$TMPDIR_T/deleted_ruleset.log"
  ONBOARD_BIN="$TMPDIR_T/onboard-bin"
  mkdir -p "$ONBOARD_BIN"
  cp "$1" "$ONBOARD_BIN/gh"
  PATH_CLEAN=$(printf '%s' "$PATH" | tr ':' '\n' | grep -v "^$MOCK_BIN$" | tr '\n' ':' | sed 's/:$//')
  PATH="$ONBOARD_BIN:$PATH_CLEAN" bash "$TEST_ONBOARD" "$2" > /dev/null 2>&1; echo $?
}

ruleset_count()         { [[ -f "$TMPDIR_T/rulesets.log"       ]] && wc -l < "$TMPDIR_T/rulesets.log"       | tr -d ' ' || echo 0; }
deleted_ruleset_count() { [[ -f "$TMPDIR_T/deleted_ruleset.log" ]] && wc -l < "$TMPDIR_T/deleted_ruleset.log" | tr -d ' ' || echo 0; }

# ── onboard: no arguments → usage error ───────────────────────────────────────

NO_ARGS_EXIT=$(bash "$TEST_ONBOARD" > /dev/null 2>&1; echo $?)
NO_ARGS_OUTPUT=$(bash "$TEST_ONBOARD" 2>&1 || true)

[[ "$NO_ARGS_EXIT" != "0" ]] \
  && ok  "onboard no-args: exits non-zero" \
  || fail "onboard no-args: exits non-zero"

printf '%s' "$NO_ARGS_OUTPUT" | grep -qi "usage" \
  && ok  "onboard no-args: prints usage" \
  || fail "onboard no-args: prints usage"

# ── onboard: own repo — two rulesets created ──────────────────────────────────

MOCK_GH_OWN="$TMPDIR_T/gh-own"
write_mock_gh "$MOCK_GH_OWN" "exists"

OWN_OUTPUT=$(run_onboard "$MOCK_GH_OWN" "${TEST_OWNER}/testrepo")
OWN_EXIT=$(run_onboard_exit "$MOCK_GH_OWN" "${TEST_OWNER}/testrepo")

# ── onboard: short form (no owner) uses current owner ────────────────────────

MOCK_GH_SHORT="$TMPDIR_T/gh-short"
write_mock_gh "$MOCK_GH_SHORT" "exists"

SHORT_EXIT=$(run_onboard_exit "$MOCK_GH_SHORT" "testrepo")

[[ "$SHORT_EXIT" == "0" ]] \
  && ok  "onboard short-form: exits 0" \
  || fail "onboard short-form: exits 0 (got $SHORT_EXIT)"

SHORT_RULESETS=$(ruleset_count)
[[ "$SHORT_RULESETS" == "2" ]] \
  && ok  "onboard short-form: two rulesets created" \
  || fail "onboard short-form: two rulesets created (got $SHORT_RULESETS)"

[[ "$OWN_EXIT" == "0" ]] \
  && ok  "onboard own-repo: exits 0" \
  || fail "onboard own-repo: exits 0 (got $OWN_EXIT)"

OWN_RULESETS=$(ruleset_count)
[[ "$OWN_RULESETS" == "2" ]] \
  && ok  "onboard own-repo: two rulesets created" \
  || fail "onboard own-repo: two rulesets created (got $OWN_RULESETS)"

printf '%s' "$OWN_OUTPUT" | grep -q "agent blocked from" \
  && ok  "onboard own-repo: output confirms ruleset" \
  || fail "onboard own-repo: output confirms ruleset"

# ── onboard: external repo where a fork already exists ────────────────────────

MOCK_GH_EXT="$TMPDIR_T/gh-ext"
write_mock_gh "$MOCK_GH_EXT" "exists"

EXT_OUTPUT=$(run_onboard "$MOCK_GH_EXT" "otherowner/extrepo")
EXT_EXIT=$(run_onboard_exit "$MOCK_GH_EXT" "otherowner/extrepo")

[[ "$EXT_EXIT" != "0" ]] \
  && ok  "onboard external-fork-exists: exits non-zero" \
  || fail "onboard external-fork-exists: exits non-zero (got $EXT_EXIT)"

printf '%s' "$EXT_OUTPUT" | grep -q "fork already exists" \
  && ok  "onboard external-fork-exists: error mentions existing fork" \
  || fail "onboard external-fork-exists: error mentions existing fork"

printf '%s' "$EXT_OUTPUT" | grep -q "${TEST_OWNER}/extrepo" \
  && ok  "onboard external-fork-exists: error suggests passing fork directly" \
  || fail "onboard external-fork-exists: error suggests passing fork directly"

# ── onboard: same-named repo exists but is NOT a fork ────────────────────────

MOCK_GH_NOTFORK="$TMPDIR_T/gh-notfork"
write_mock_gh "$MOCK_GH_NOTFORK" "not-a-fork"

NOTFORK_OUTPUT=$(run_onboard "$MOCK_GH_NOTFORK" "otherowner/extrepo")
NOTFORK_EXIT=$(run_onboard_exit "$MOCK_GH_NOTFORK" "otherowner/extrepo")

[[ "$NOTFORK_EXIT" != "0" ]] \
  && ok  "onboard collision-not-fork: exits non-zero" \
  || fail "onboard collision-not-fork: exits non-zero"

printf '%s' "$NOTFORK_OUTPUT" | grep -qi "not a fork" \
  && ok  "onboard collision-not-fork: error mentions 'not a fork'" \
  || fail "onboard collision-not-fork: error mentions 'not a fork'"


# ── onboard: existing same-named ruleset is replaced ─────────────────────────

MOCK_GH_REPLACE="$TMPDIR_T/gh-replace"
write_mock_gh "$MOCK_GH_REPLACE" "exists" "has-existing-ruleset"

REPLACE_OUTPUT=$(run_onboard "$MOCK_GH_REPLACE" "${TEST_OWNER}/testrepo")
REPLACE_EXIT=$(run_onboard_exit "$MOCK_GH_REPLACE" "${TEST_OWNER}/testrepo")

[[ "$REPLACE_EXIT" == "0" ]] \
  && ok  "onboard replace-ruleset: exits 0" \
  || fail "onboard replace-ruleset: exits 0 (got $REPLACE_EXIT)"

REPLACE_DELETED=$(deleted_ruleset_count)
[[ "$REPLACE_DELETED" == "2" ]] \
  && ok  "onboard replace-ruleset: both old rulesets deleted" \
  || fail "onboard replace-ruleset: both old rulesets deleted (got $REPLACE_DELETED)"

REPLACE_CREATED=$(ruleset_count)
[[ "$REPLACE_CREATED" == "2" ]] \
  && ok  "onboard replace-ruleset: both new rulesets created" \
  || fail "onboard replace-ruleset: both new rulesets created (got $REPLACE_CREATED)"

printf '%s' "$REPLACE_OUTPUT" | grep -qi "replacing existing" \
  && ok  "onboard replace-ruleset: output mentions replacing" \
  || fail "onboard replace-ruleset: output mentions replacing"

# ═══════════════════════════════════════════════════════════════════════════════
# audit.sh tests
# ═══════════════════════════════════════════════════════════════════════════════

TEST_AUDIT="$DIR/internal/audit.sh"

bash -n "$TEST_AUDIT" 2>/dev/null \
  && ok  "syntax: audit.sh" \
  || fail "syntax: audit.sh"

# Helper: run audit.sh with a mock curl and given env vars.
# $1 = curl mock path, $2 = GH_APP_ID, $3 = GH_APP_PEM_B64
# $4 = workdir (optional; for inventory tests — must contain a bare git repo)
# $5 = GITHUB_TOKEN (optional; set to enable inventory update)
run_audit() {
  local curl_mock="$1" app_id="$2" pem_b64="$3" workdir="${4:-$TMPDIR_T}" token="${5:-}"
  local audit_bin="$TMPDIR_T/audit-bin"
  mkdir -p "$audit_bin"
  cp "$curl_mock" "$audit_bin/curl"
  GH_APP_ID="$app_id" GH_APP_PEM_B64="$pem_b64" GITHUB_TOKEN="$token" \
    PATH="$audit_bin:$PATH" bash "$TEST_AUDIT" 2>&1 || true
}
run_audit_exit() {
  local curl_mock="$1" app_id="$2" pem_b64="$3" workdir="${4:-$TMPDIR_T}" token="${5:-}"
  local audit_bin="$TMPDIR_T/audit-bin"
  mkdir -p "$audit_bin"
  cp "$curl_mock" "$audit_bin/curl"
  GH_APP_ID="$app_id" GH_APP_PEM_B64="$pem_b64" GITHUB_TOKEN="$token" \
    PATH="$audit_bin:$PATH" bash "$TEST_AUDIT" > /dev/null 2>&1; echo $?
}

# A valid base64-encoded PEM for JWT signing
AUDIT_PEM_B64=$(base64 < "$TEST_KEY_FILE" | tr -d '\n')

# ── audit: missing secrets → exits non-zero with error ───────────────────────

NOSEC_BIN="$TMPDIR_T/audit-nosec-curl"
printf '#!/usr/bin/env bash\nprintf "[]"' > "$NOSEC_BIN"; chmod +x "$NOSEC_BIN"

NOSEC_EXIT=$(run_audit_exit "$NOSEC_BIN" "" "")
NOSEC_OUTPUT=$(run_audit "$NOSEC_BIN" "" "")

[[ "$NOSEC_EXIT" != "0" ]] \
  && ok  "audit missing-secrets: exits non-zero" \
  || fail "audit missing-secrets: exits non-zero"

printf '%s' "$NOSEC_OUTPUT" | grep -q "GH_APP_ID" \
  && ok  "audit missing-secrets: error mentions GH_APP_ID" \
  || fail "audit missing-secrets: error mentions GH_APP_ID"

# ── audit: no installation found → exits non-zero ────────────────────────────

NOINST_CURL="$TMPDIR_T/audit-noinst-curl"
cat > "$NOINST_CURL" << 'EOF'
#!/usr/bin/env bash
printf '[]'
EOF
chmod +x "$NOINST_CURL"

NOINST_EXIT=$(run_audit_exit "$NOINST_CURL" "$TEST_APP_ID" "$AUDIT_PEM_B64")
NOINST_OUTPUT=$(run_audit "$NOINST_CURL" "$TEST_APP_ID" "$AUDIT_PEM_B64")

[[ "$NOINST_EXIT" != "0" ]] \
  && ok  "audit no-installation: exits non-zero" \
  || fail "audit no-installation: exits non-zero"

printf '%s' "$NOINST_OUTPUT" | grep -q "no installation" \
  && ok  "audit no-installation: error mentions no installation" \
  || fail "audit no-installation: error mentions no installation"

# ── audit: all repos protected → exits 0, prints PASS ────────────────────────

ALLPASS_CURL="$TMPDIR_T/audit-allpass-curl"
cat > "$ALLPASS_CURL" << MOCKEOF
#!/usr/bin/env bash
if [[ "\$*" == *"/app/installations"* && "\$*" != *"access_tokens"* ]]; then
  printf '[{"id":42}]'
elif [[ "\$*" == *"access_tokens"* ]]; then
  printf '{"token":"ghs_mock"}'
elif [[ "\$*" == *"/installation/repositories"* ]]; then
  printf '{"repositories":[{"full_name":"${TEST_OWNER}/repo1"},{"full_name":"${TEST_OWNER}/repo2"}]}'
elif [[ "\$*" == *"/rulesets"* ]]; then
  printf '[{"name":"agent-gh-access-apps-blocked-from-non-ai-branches"},{"name":"agent-gh-access-apps-must-sign"}]'
fi
MOCKEOF
chmod +x "$ALLPASS_CURL"

ALLPASS_EXIT=$(run_audit_exit "$ALLPASS_CURL" "$TEST_APP_ID" "$AUDIT_PEM_B64")
ALLPASS_OUTPUT=$(run_audit "$ALLPASS_CURL" "$TEST_APP_ID" "$AUDIT_PEM_B64")

[[ "$ALLPASS_EXIT" == "0" ]] \
  && ok  "audit all-protected: exits 0" \
  || fail "audit all-protected: exits 0 (got $ALLPASS_EXIT)"

printf '%s' "$ALLPASS_OUTPUT" | grep -q "PASS  ${TEST_OWNER}/repo1" \
  && ok  "audit all-protected: prints PASS for each repo" \
  || fail "audit all-protected: prints PASS for each repo"

printf '%s' "$ALLPASS_OUTPUT" | grep -q "All installed repos" \
  && ok  "audit all-protected: prints success summary" \
  || fail "audit all-protected: prints success summary"

# ── audit: one repo missing rulesets → exits non-zero, prints FAIL ───────────

ONEFAIL_CURL="$TMPDIR_T/audit-onefail-curl"
cat > "$ONEFAIL_CURL" << MOCKEOF
#!/usr/bin/env bash
if [[ "\$*" == *"/app/installations"* && "\$*" != *"access_tokens"* ]]; then
  printf '[{"id":42}]'
elif [[ "\$*" == *"access_tokens"* ]]; then
  printf '{"token":"ghs_mock"}'
elif [[ "\$*" == *"/installation/repositories"* ]]; then
  printf '{"repositories":[{"full_name":"${TEST_OWNER}/good"},{"full_name":"${TEST_OWNER}/bad"}]}'
elif [[ "\$*" == *"/${TEST_OWNER}/good/rulesets"* ]]; then
  printf '[{"name":"agent-gh-access-apps-blocked-from-non-ai-branches"},{"name":"agent-gh-access-apps-must-sign"}]'
elif [[ "\$*" == *"/${TEST_OWNER}/bad/rulesets"* ]]; then
  printf '[]'
fi
MOCKEOF
chmod +x "$ONEFAIL_CURL"

ONEFAIL_EXIT=$(run_audit_exit "$ONEFAIL_CURL" "$TEST_APP_ID" "$AUDIT_PEM_B64")
ONEFAIL_OUTPUT=$(run_audit "$ONEFAIL_CURL" "$TEST_APP_ID" "$AUDIT_PEM_B64")

[[ "$ONEFAIL_EXIT" != "0" ]] \
  && ok  "audit one-failing: exits non-zero" \
  || fail "audit one-failing: exits non-zero (got $ONEFAIL_EXIT)"

printf '%s' "$ONEFAIL_OUTPUT" | grep -q "PASS  ${TEST_OWNER}/good" \
  && ok  "audit one-failing: prints PASS for protected repo" \
  || fail "audit one-failing: prints PASS for protected repo"

printf '%s' "$ONEFAIL_OUTPUT" | grep -q "FAIL  ${TEST_OWNER}/bad" \
  && ok  "audit one-failing: prints FAIL for unprotected repo" \
  || fail "audit one-failing: prints FAIL for unprotected repo"

printf '%s' "$ONEFAIL_OUTPUT" | grep -q "onboard-repo.sh" \
  && ok  "audit one-failing: error mentions onboard-repo.sh" \
  || fail "audit one-failing: error mentions onboard-repo.sh"

# ═══════════════════════════════════════════════════════════════════════════════
# audit.sh inventory tests (GITHUB_TOKEN path)
# ═══════════════════════════════════════════════════════════════════════════════

# Set up a minimal git repo so audit.sh can commit inventory updates.
INV_REPO="$TMPDIR_T/inv-repo"
mkdir -p "$INV_REPO"
git -C "$INV_REPO" init -q
git -C "$INV_REPO" config user.email "test@test"
git -C "$INV_REPO" config user.name  "test"
# Seed with an initial commit so HEAD exists
touch "$INV_REPO/.keep"
git -C "$INV_REPO" add .keep
git -C "$INV_REPO" commit -q -m "init"

# Mock git that delegates to real git but suppresses push
REAL_GIT=$(command -v git)
AUDIT_GIT_BIN="$TMPDIR_T/audit-git-bin"
mkdir -p "$AUDIT_GIT_BIN"
cat > "$AUDIT_GIT_BIN/git" << GITEOF
#!/usr/bin/env bash
if [[ "\$1" == "push" ]]; then exit 0; fi
exec "${REAL_GIT}" "\$@"
GITEOF
chmod +x "$AUDIT_GIT_BIN/git"

# curl mock returning two repos, both protected
INV_CURL="$TMPDIR_T/audit-inv-curl"
cat > "$INV_CURL" << MOCKEOF
#!/usr/bin/env bash
if [[ "\$*" == *"/app/installations"* && "\$*" != *"access_tokens"* ]]; then
  printf '[{"id":42}]'
elif [[ "\$*" == *"access_tokens"* ]]; then
  printf '{"token":"ghs_mock"}'
elif [[ "\$*" == *"/installation/repositories"* ]]; then
  printf '{"repositories":[{"full_name":"${TEST_OWNER}/repo1"},{"full_name":"${TEST_OWNER}/repo2"}]}'
elif [[ "\$*" == *"/rulesets"* ]]; then
  printf '[{"name":"agent-gh-access-apps-blocked-from-non-ai-branches"},{"name":"agent-gh-access-apps-must-sign"}]'
fi
MOCKEOF
chmod +x "$INV_CURL"

# Run audit twice with GITHUB_TOKEN set to test cumulative behaviour
cp "$INV_CURL" "$TMPDIR_T/audit-bin/curl"
for _run in 1 2; do
  (cd "$INV_REPO" && \
    GH_APP_ID="$TEST_APP_ID" GH_APP_PEM_B64="$AUDIT_PEM_B64" GITHUB_TOKEN="fake" \
    PATH="$AUDIT_GIT_BIN:$TMPDIR_T/audit-bin:$PATH" \
    bash "$TEST_AUDIT" > /dev/null 2>&1 || true)
done

INV_FILE="$INV_REPO/onboarded-repos.txt"

[[ -f "$INV_FILE" ]] \
  && ok  "audit inventory: onboarded-repos.txt created" \
  || fail "audit inventory: onboarded-repos.txt created"

head -1 "$INV_FILE" | grep -q "^# app-id:${TEST_APP_ID}$" \
  && ok  "audit inventory: first line is app-id comment" \
  || fail "audit inventory: first line is app-id comment"

grep -qx "${TEST_OWNER}/repo1" "$INV_FILE" \
  && ok  "audit inventory: repo1 present" \
  || fail "audit inventory: repo1 present"

grep -qx "${TEST_OWNER}/repo2" "$INV_FILE" \
  && ok  "audit inventory: repo2 present" \
  || fail "audit inventory: repo2 present"

# Verify no duplicates after two runs
REPO1_COUNT=$(grep -cx "${TEST_OWNER}/repo1" "$INV_FILE" || true)
[[ "$REPO1_COUNT" == "1" ]] \
  && ok  "audit inventory: no duplicate entries after two runs" \
  || fail "audit inventory: no duplicate entries after two runs (count=$REPO1_COUNT)"

# ── audit inventory: app-id change resets file ───────────────────────────────

NEW_APP_ID="111222"
cp "$INV_CURL" "$TMPDIR_T/audit-bin/curl"
(cd "$INV_REPO" && \
  GH_APP_ID="$NEW_APP_ID" GH_APP_PEM_B64="$AUDIT_PEM_B64" GITHUB_TOKEN="fake" \
  PATH="$AUDIT_GIT_BIN:$TMPDIR_T/audit-bin:$PATH" \
  bash "$TEST_AUDIT" > /dev/null 2>&1 || true)

head -1 "$INV_FILE" | grep -q "^# app-id:${NEW_APP_ID}$" \
  && ok  "audit inventory: app-id change resets header" \
  || fail "audit inventory: app-id change resets header"

grep -qx "${TEST_OWNER}/repo1" "$INV_FILE" \
  && ok  "audit inventory: repos repopulated after reset" \
  || fail "audit inventory: repos repopulated after reset"

# Old app-id must not appear anywhere in the file
grep -q "app-id:${TEST_APP_ID}" "$INV_FILE" \
  && fail "audit inventory: old app-id still present after reset" \
  || ok  "audit inventory: old app-id gone after reset"

# ═══════════════════════════════════════════════════════════════════════════════
# cleanup.sh tests
# ═══════════════════════════════════════════════════════════════════════════════

TEST_CLEANUP="$DIR/cleanup.sh"

bash -n "$TEST_CLEANUP" 2>/dev/null \
  && ok  "syntax: cleanup.sh" \
  || fail "syntax: cleanup.sh"

# Shared mock gh for cleanup tests: handles user login, secret existence/deletion,
# ruleset listing/deletion. $1 controls secret existence ("has-secrets"|"no-secrets").
write_cleanup_mock_gh() {
  local mock_path="$1" secret_state="${2:-has-secrets}"
  cat > "$mock_path" << GHEOF
#!/usr/bin/env bash
args="\$*"
if [[ "\$args" == *"user"* && "\$args" == *".login"* ]]; then
  printf '%s' "${TEST_OWNER}"
  exit 0
fi
if [[ "\$args" == *"secrets/GH_APP_ID"* && "\$args" != *"DELETE"* ]]; then
  [[ "${secret_state}" == "has-secrets" ]] && exit 0 || exit 1
fi
if [[ "\$args" == *"secrets/GH_APP_PEM"* && "\$args" != *"DELETE"* ]]; then
  [[ "${secret_state}" == "has-secrets" ]] && exit 0 || exit 1
fi
if [[ "\$args" == *"--method DELETE"* && "\$args" == *"secrets"* ]]; then
  echo "secret-deleted" >> "${TMPDIR_T}/cleanup-secrets.log"
  exit 0
fi
if [[ "\$args" == *"/rulesets"* && "\$args" != *"--method"* ]]; then
  printf '[{"name":"agent-gh-access-apps-blocked-from-non-ai-branches","id":10},{"name":"agent-gh-access-apps-must-sign","id":11}]'
  exit 0
fi
if [[ "\$args" == *"--method DELETE"* && "\$args" == *"rulesets"* ]]; then
  echo "ruleset-deleted" >> "${TMPDIR_T}/cleanup-rulesets.log"
  exit 0
fi
exit 0
GHEOF
  chmod +x "$mock_path"
}

# Write a valid inventory file for cleanup tests
CLEANUP_INVENTORY="$TMPDIR_T/cleanup-inventory.txt"
printf '# app-id:%s\n%s/repo1\n%s/repo2\n' \
  "$TEST_APP_ID" "$TEST_OWNER" "$TEST_OWNER" > "$CLEANUP_INVENTORY"

# curl mock: app is gone (404)
CLEANUP_CURL_GONE="$TMPDIR_T/cleanup-curl-gone"
cat > "$CLEANUP_CURL_GONE" << 'EOF'
#!/usr/bin/env bash
# Return 404 for app existence check
printf '' ; exit 0
# (curl -w "%{http_code}" prints the code; simulate by writing to stdout)
EOF
# Use a proper curl mock that outputs 404 as the http_code
cat > "$CLEANUP_CURL_GONE" << 'EOF'
#!/usr/bin/env bash
if [[ "$*" == *"-w"* && "$*" == *"%{http_code}"* ]]; then
  printf '404'
fi
EOF
chmod +x "$CLEANUP_CURL_GONE"

run_cleanup() {
  local gh_mock="$1" curl_mock="$2" inventory="$3"
  rm -f "$TMPDIR_T/cleanup-secrets.log" "$TMPDIR_T/cleanup-rulesets.log"
  local bin="$TMPDIR_T/cleanup-bin"
  mkdir -p "$bin"
  cp "$gh_mock"   "$bin/gh"
  cp "$curl_mock" "$bin/curl"
  PATH="$bin:$PATH" bash "$TEST_CLEANUP" < /dev/null 2>&1 || true
}
run_cleanup_exit() {
  local gh_mock="$1" curl_mock="$2" inventory="$3"
  rm -f "$TMPDIR_T/cleanup-secrets.log" "$TMPDIR_T/cleanup-rulesets.log"
  local bin="$TMPDIR_T/cleanup-bin"
  mkdir -p "$bin"
  cp "$gh_mock"   "$bin/gh"
  cp "$curl_mock" "$bin/curl"
  PATH="$bin:$PATH" bash "$TEST_CLEANUP" < /dev/null > /dev/null 2>&1; echo $?
}
cleanup_secret_count()  { [[ -f "$TMPDIR_T/cleanup-secrets.log"  ]] && wc -l < "$TMPDIR_T/cleanup-secrets.log"  | tr -d ' ' || echo 0; }
cleanup_ruleset_count() { [[ -f "$TMPDIR_T/cleanup-rulesets.log" ]] && wc -l < "$TMPDIR_T/cleanup-rulesets.log" | tr -d ' ' || echo 0; }

# ── cleanup: missing inventory → exits non-zero ───────────────────────────────

MOCK_GH_CLEAN="$TMPDIR_T/cleanup-gh-clean"
write_cleanup_mock_gh "$MOCK_GH_CLEAN"

NOINV_EXIT=$(cd "$TMPDIR_T" && \
  PATH="$TMPDIR_T/cleanup-bin:$PATH" \
  bash "$TEST_CLEANUP" < /dev/null > /dev/null 2>&1; echo $?)

[[ "$NOINV_EXIT" != "0" ]] \
  && ok  "cleanup no-inventory: exits non-zero" \
  || fail "cleanup no-inventory: exits non-zero"

# ── cleanup: app confirmed gone → deletes secrets and rulesets ────────────────

(cd "$TMPDIR_T" && cp "$CLEANUP_INVENTORY" onboarded-repos.txt)

MOCK_GH_FULL="$TMPDIR_T/cleanup-gh-full"
write_cleanup_mock_gh "$MOCK_GH_FULL"

FULL_OUTPUT=$(cd "$TMPDIR_T" && run_cleanup "$MOCK_GH_FULL" "$CLEANUP_CURL_GONE" "$CLEANUP_INVENTORY")
FULL_EXIT=$(cd "$TMPDIR_T" && run_cleanup_exit "$MOCK_GH_FULL" "$CLEANUP_CURL_GONE" "$CLEANUP_INVENTORY")

[[ "$FULL_EXIT" == "0" ]] \
  && ok  "cleanup full: exits 0" \
  || fail "cleanup full: exits 0 (got $FULL_EXIT)"

SECRET_COUNT=$(cleanup_secret_count)
[[ "$SECRET_COUNT" == "2" ]] \
  && ok  "cleanup full: both secrets deleted" \
  || fail "cleanup full: both secrets deleted (got $SECRET_COUNT)"

RULESET_COUNT=$(cleanup_ruleset_count)
[[ "$RULESET_COUNT" == "4" ]] \
  && ok  "cleanup full: all rulesets deleted (2 repos × 2 rulesets)" \
  || fail "cleanup full: all rulesets deleted (got $RULESET_COUNT)"

printf '%s' "$FULL_OUTPUT" | grep -q "Cleanup complete" \
  && ok  "cleanup full: prints completion message" \
  || fail "cleanup full: prints completion message"

# ── cleanup: app still exists → prompts user ──────────────────────────────────

CLEANUP_CURL_EXISTS="$TMPDIR_T/cleanup-curl-exists"
cat > "$CLEANUP_CURL_EXISTS" << 'EOF'
#!/usr/bin/env bash
if [[ "$*" == *"-w"* && "$*" == *"%{http_code}"* ]]; then
  printf '200'
fi
EOF
chmod +x "$CLEANUP_CURL_EXISTS"

EXISTS_OUTPUT=$(cd "$TMPDIR_T" && run_cleanup "$MOCK_GH_FULL" "$CLEANUP_CURL_EXISTS" "$CLEANUP_INVENTORY")

printf '%s' "$EXISTS_OUTPUT" | grep -qi "still exists" \
  && ok  "cleanup app-exists: warns app still exists" \
  || fail "cleanup app-exists: warns app still exists"

printf '%s' "$EXISTS_OUTPUT" | grep -qi "Delete it at" \
  && ok  "cleanup app-exists: prints deletion URL" \
  || fail "cleanup app-exists: prints deletion URL"

# ── Summary ───────────────────────────────────────────────────────────────────

echo ""
echo "────────────────────────────────"
printf "Results: %d passed, %d failed\n" "$PASS" "$FAIL"
if [[ ${#ERRORS[@]} -gt 0 ]]; then
  echo ""
  echo "Failed:"
  for e in "${ERRORS[@]}"; do
    printf "  ✗ %s\n" "$e"
  done
  echo ""
  exit 1
fi
