#!/usr/bin/env bash
# test.sh — offline tests for agent-github-access scripts
#
# Runs install.sh for real (with mocked gh and browser) to generate
# authenticate-github.sh, then tests its behaviour and onboard-repo.sh with
# mocked network calls.  No real GitHub API calls are made.
#
# Requirements: bash, python3, openssl, jq, curl, base64
set -uo pipefail

DIR="$(cd "$(dirname "$0")/.." && pwd)"
PASS=0; FAIL=0
ERRORS=()

ok()   { PASS=$((PASS+1)); printf "PASS  %s\n" "$1"; }
fail() { FAIL=$((FAIL+1)); ERRORS+=("$1"); printf "FAIL  %s\n" "$1"; }

# ── Setup ─────────────────────────────────────────────────────────────────────

TMPDIR_T=$(mktemp -d)
trap 'rm -rf "$TMPDIR_T"' EXIT

TEST_APP_ID="999888"
TEST_OWNER="testowner"
TEST_SLUG="${TEST_OWNER}-agent"

# A real RSA key is required — openssl uses it to sign JWTs in the generated script.
TEST_KEY_FILE="$TMPDIR_T/test.pem"
openssl genrsa -out "$TEST_KEY_FILE" 2048 2>/dev/null

# Write the fake /app-manifests/.../conversions response to a file so the mock
# gh can cat it.  python3 handles JSON-escaping the PEM (newlines etc).
CONVERSION_JSON="$TMPDIR_T/conversion.json"
python3 - "$TEST_KEY_FILE" "$TEST_APP_ID" "$TEST_SLUG" "$CONVERSION_JSON" << 'PYEOF'
import json, sys
key_file, app_id, slug, out = sys.argv[1:]
pem = open(key_file).read()
with open(out, 'w') as f:
    json.dump({"id": int(app_id), "slug": slug, "pem": pem}, f)
PYEOF

# ── Mock binaries for install.sh ─────────────────────────────────────

MAIN_BIN="$TMPDIR_T/main-bin"
mkdir -p "$MAIN_BIN"

# gh: handles all calls made by install.sh (which now also runs
# onboard-repo.sh for the fork before app creation).
cat > "$MAIN_BIN/gh" << GHEOF
#!/usr/bin/env bash
args="\$*"
if [[ "\$args" == *"user"* && "\$args" == *".login"* ]]; then
  printf '%s' "${TEST_OWNER}"
elif [[ "\$args" == *"secrets/GH_APP_ID"* && "\$args" != *"--method"* ]]; then
  # Secret existence check — return 404 (not yet set) so app creation proceeds
  exit 1
elif [[ "\$args" == *"secrets/public-key"* ]]; then
  # Return a fake libsodium public key (32 bytes, base64-encoded)
  printf '{"key_id":"1234","key":"hiNFHFRJGnHP5UNKhXkMEEI7iNLMFHmqhAeH3xQBtUE="}'
elif [[ "\$args" == *"secrets/"* && "\$args" == *"--method PUT"* ]]; then
  exit 0
elif [[ "\$args" == *"rulesets"* && "\$args" == *"--method DELETE"* ]]; then
  exit 0
elif [[ "\$args" == *"rulesets"* && "\$args" == *"--method POST"* ]]; then
  printf '{"id":1}'
elif [[ "\$args" == *"rulesets"* ]]; then
  # GET rulesets — return empty list (no pre-existing rulesets)
  printf '[]'
elif [[ "\$args" == *"workflow run"* ]]; then
  exit 0
fi
exit 0
GHEOF
chmod +x "$MAIN_BIN/gh"

# curl: intercept the unauthenticated app-manifests conversion call; pass everything else through.
REAL_CURL=$(command -v curl)
cat > "$MAIN_BIN/curl" << CURLEOF
#!/usr/bin/env bash
if [[ "\$*" == *"app-manifests"* ]]; then
  cat "${CONVERSION_JSON}"
else
  "${REAL_CURL}" "\$@"
fi
CURLEOF
chmod +x "$MAIN_BIN/curl"

# xdg-open: for file:// URLs, simulate the OAuth callback instead of opening a
# browser. The real Python HTTP server is already running and will write the code
# to CODEFILE, unblocking `wait $SERVER_PID` in install.sh.
# For the https:// installation URL opened at the end, do nothing.
cat > "$MAIN_BIN/xdg-open" << 'XDGEOF'
#!/usr/bin/env bash
if [[ "$1" == http://localhost:* ]]; then
  PORT="${1#http://localhost:}"
  PORT="${PORT%%/*}"
  sleep 0.3
  curl -sf "http://localhost:${PORT}/callback?code=testcode123" > /dev/null || true
fi
XDGEOF
chmod +x "$MAIN_BIN/xdg-open"

# ── 1. Syntax: install.sh ────────────────────────────────────────────

bash -n "$DIR/install.sh" 2>/dev/null \
  && ok  "syntax: install.sh" \
  || fail "syntax: install.sh"

# ── 2. Run install.sh to generate authenticate-github.sh ─────────────
# Pass TEST_OWNER as the username arg to skip the multi-account check.
# Run from a work dir so the generated script lands there, not in the repo root.

WORK="$TMPDIR_T/work"
mkdir -p "$WORK"

GEN_OUTPUT=$(cd "$WORK" && printf 'y\ny\n' | PATH="$MAIN_BIN:$PATH" bash "$DIR/install.sh" "$TEST_OWNER" 2>&1) || true

TEST_AUTH="$WORK/authenticate-github.sh"
# onboard-repo.sh is now a static file in the repo (not generated by install.sh)
TEST_ONBOARD="$DIR/onboard-repo.sh"

if [[ -f "$TEST_AUTH" ]]; then
  ok  "generate: authenticate-github.sh produced"
else
  fail "generate: authenticate-github.sh produced"
fi

# ── 3. Syntax: generated and static scripts ────────────────────────────────────

bash -n "$TEST_AUTH" 2>/dev/null \
  && ok  "syntax: authenticate-github.sh" \
  || fail "syntax: authenticate-github.sh"

bash -n "$TEST_ONBOARD" 2>/dev/null \
  && ok  "syntax: onboard-repo.sh" \
  || fail "syntax: onboard-repo.sh"

# Save original onboard-repo.sh so nondefault install runs (which call
# "sed -i" on it) can be restored without breaking later onboard tests.
ONBOARD_ORIG=$(cat "$DIR/onboard-repo.sh")

# ── 3b. Nondefault prompt: actions=n, verified=y ──────────────────────────────
# Answering 'n' to actions:write and 'y' to verified commits.
# The generated authenticate-github.sh should still be produced and contain
# the COMMIT METHOD block (verified=y) but use actions:read in the manifest.

WORK_NO_ACTIONS="$TMPDIR_T/work-no-actions"
mkdir -p "$WORK_NO_ACTIONS"

printf 'n\ny\n' | PATH="$MAIN_BIN:$PATH" bash "$DIR/install.sh" "$TEST_OWNER" \
  > "$TMPDIR_T/gen-no-actions.log" 2>&1 || true

AUTH_NO_ACTIONS="$WORK_NO_ACTIONS/authenticate-github.sh"
# install.sh always writes authenticate-github.sh in the current directory
cp "$WORK/authenticate-github.sh" "$AUTH_NO_ACTIONS" 2>/dev/null || true
# Re-generate in correct workdir
rm -f "$WORK_NO_ACTIONS/authenticate-github.sh"
(cd "$WORK_NO_ACTIONS" && printf 'n\ny\n' | PATH="$MAIN_BIN:$PATH" bash "$DIR/install.sh" "$TEST_OWNER" > /dev/null 2>&1) || true

if [[ -f "$AUTH_NO_ACTIONS" ]]; then
  ok  "generate actions=n: authenticate-github.sh produced"
else
  fail "generate actions=n: authenticate-github.sh produced"
fi

bash -n "$AUTH_NO_ACTIONS" 2>/dev/null \
  && ok  "syntax actions=n: authenticate-github.sh" \
  || fail "syntax actions=n: authenticate-github.sh"

# Restore onboard-repo.sh mutated by the install run above
printf '%s' "$ONBOARD_ORIG" > "$DIR/onboard-repo.sh"

# ── 3c. Nondefault prompt: actions=y, verified=n ──────────────────────────────
# Answering 'y' to actions:write and 'n' to verified commits.
# The generated authenticate-github.sh should omit the COMMIT METHOD block
# and check only one ruleset (no must-sign filter).

WORK_NO_VERIFIED="$TMPDIR_T/work-no-verified"
mkdir -p "$WORK_NO_VERIFIED"
(cd "$WORK_NO_VERIFIED" && printf 'y\nn\n' | PATH="$MAIN_BIN:$PATH" bash "$DIR/install.sh" "$TEST_OWNER" > /dev/null 2>&1) || true

AUTH_NO_VERIFIED="$WORK_NO_VERIFIED/authenticate-github.sh"

if [[ -f "$AUTH_NO_VERIFIED" ]]; then
  ok  "generate verified=n: authenticate-github.sh produced"
else
  fail "generate verified=n: authenticate-github.sh produced"
fi

bash -n "$AUTH_NO_VERIFIED" 2>/dev/null \
  && ok  "syntax verified=n: authenticate-github.sh" \
  || fail "syntax verified=n: authenticate-github.sh"

grep -q "COMMIT METHOD" "$AUTH_NO_VERIFIED" \
  && fail "generate verified=n: commit method block absent" \
  || ok  "generate verified=n: commit method block absent"

# Restore onboard-repo.sh mutated by the verified=n install run above
printf '%s' "$ONBOARD_ORIG" > "$DIR/onboard-repo.sh"

# ── 4. JWT format ─────────────────────────────────────────────────────────────
# Run the JWT construction logic in a subshell using the test key.  No network.

JWT_RESULT=$(bash << BEOF
set -euo pipefail
APP_PEM=\$(cat "$TEST_KEY_FILE")
APP_ID="$TEST_APP_ID"
NOW=\$(date +%s)
EXP=\$((NOW + 540))

b64url() { base64 | tr '+/' '-_' | tr -d '=\n'; }
HEADER=\$(printf '%s' '{"alg":"RS256","typ":"JWT"}' | b64url)
PAYLOAD=\$(printf '{"iat":%d,"exp":%d,"iss":%d}' "\$NOW" "\$EXP" "\$APP_ID" | b64url)

TMPKEY=\$(mktemp)
chmod 600 "\$TMPKEY"
printf '%s' "\$APP_PEM" > "\$TMPKEY"
SIG=\$(printf '%s.%s' "\$HEADER" "\$PAYLOAD" | openssl dgst -binary -sha256 -sign "\$TMPKEY" | b64url)
rm -f "\$TMPKEY"

printf '%s.%s.%s' "\$HEADER" "\$PAYLOAD" "\$SIG"
BEOF
)

if [[ "$JWT_RESULT" =~ ^[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+\.[A-Za-z0-9_-]+$ ]]; then
  ok  "jwt: three-part base64url format"
else
  fail "jwt: three-part base64url format (got: ${JWT_RESULT:0:40}…)"
fi

JWT_HEADER_PART="${JWT_RESULT%%.*}"
PADDED="${JWT_HEADER_PART}==="
DECODED=$(printf '%s' "$PADDED" | tr '_-' '/+' | base64 -d 2>/dev/null || \
          printf '%s' "$PADDED" | tr '_-' '/+' | base64 -D 2>/dev/null)
if printf '%s' "$DECODED" | grep -q '"RS256"'; then
  ok  "jwt: header contains RS256"
else
  fail "jwt: header contains RS256 (got: $DECODED)"
fi

# ── Mock bin for authenticate-github.sh tests (curl-based) ────────────────────

MOCK_BIN="$TMPDIR_T/bin"
mkdir -p "$MOCK_BIN"

# ── 5. Error: no installations ────────────────────────────────────────────────

cat > "$MOCK_BIN/curl" << 'EOF'
#!/usr/bin/env bash
printf '[]'
exit 0
EOF
chmod +x "$MOCK_BIN/curl"

NO_INST_OUTPUT=$(PATH="$MOCK_BIN:$PATH" bash "$TEST_AUTH" 2>&1 || true)
NO_INST_EXIT=$(PATH="$MOCK_BIN:$PATH" bash "$TEST_AUTH" > /dev/null 2>&1; echo $?)

[[ "$NO_INST_EXIT" != "0" ]] \
  && ok  "no-installations: exits non-zero" \
  || fail "no-installations: exits non-zero"

printf '%s' "$NO_INST_OUTPUT" | grep -q "no repositories configured" \
  && ok  "no-installations: error mentions 'no repositories configured'" \
  || fail "no-installations: error mentions 'no repositories configured'"

printf '%s' "$NO_INST_OUTPUT" | grep -q "trusted machine" \
  && ok  "no-installations: error mentions 'trusted machine'" \
  || fail "no-installations: error mentions 'trusted machine'"

# ── 6. Error: no protected repos ──────────────────────────────────────────────

cat > "$MOCK_BIN/curl" << MOCKEOF
#!/usr/bin/env bash
if [[ "\$*" == *"/app/installations" ]]; then
  printf '[{"id":42,"account":{"login":"${TEST_OWNER}","type":"User"}}]'
elif [[ "\$*" == *"/access_tokens" ]]; then
  printf '{"token":"ghs_faketoken123"}'
elif [[ "\$*" == *"/installation/repositories" ]]; then
  printf '{"repositories":[{"id":101,"full_name":"${TEST_OWNER}/testrepo"}]}'
elif [[ "\$*" == */rulesets ]]; then
  printf '[]'
else
  printf '{}'
fi
exit 0
MOCKEOF
chmod +x "$MOCK_BIN/curl"

NO_RULES_OUTPUT=$(PATH="$MOCK_BIN:$PATH" bash "$TEST_AUTH" 2>&1 || true)
NO_RULES_EXIT=$(PATH="$MOCK_BIN:$PATH" bash "$TEST_AUTH" > /dev/null 2>&1; echo $?)

[[ "$NO_RULES_EXIT" != "0" ]] \
  && ok  "no-protected-repos: exits non-zero" \
  || fail "no-protected-repos: exits non-zero"

printf '%s' "$NO_RULES_OUTPUT" | grep -qi "onboard-repo" \
  && ok  "no-protected-repos: error mentions onboard-repo" \
  || fail "no-protected-repos: error mentions onboard-repo"

# ── 7. Output content: global memory bookends and branch prefix ───────────────

cat > "$MOCK_BIN/curl" << MOCKEOF
#!/usr/bin/env bash
if [[ "\$*" == *"/app/installations" ]]; then
  printf '[{"id":42,"account":{"login":"${TEST_OWNER}","type":"User"}}]'
elif [[ "\$*" == *"/access_tokens" ]]; then
  printf '{"token":"ghs_faketoken123"}'
elif [[ "\$*" == *"/installation/repositories" ]]; then
  printf '{"repositories":[{"id":101,"full_name":"${TEST_OWNER}/testrepo"}]}'
elif [[ "\$*" == */rulesets ]]; then
  printf '[{"name":"agent-gh-access-apps-blocked-from-non-ai-branches"},{"name":"agent-gh-access-apps-must-sign"}]'
else
  printf '{}'
fi
exit 0
MOCKEOF
chmod +x "$MOCK_BIN/curl"

cat > "$MOCK_BIN/git" << 'EOF'
#!/usr/bin/env bash
exit 0
EOF
chmod +x "$MOCK_BIN/git"

cat > "$MOCK_BIN/gh" << 'EOF'
#!/usr/bin/env bash
exit 0
EOF
chmod +x "$MOCK_BIN/gh"

SUCCESS_OUTPUT=$(PATH="$MOCK_BIN:$PATH" bash "$TEST_AUTH" 2>&1 || true)

printf '%s' "$SUCCESS_OUTPUT" | grep -q "STORE IN GLOBAL MEMORY" \
  && ok  "output: opens with STORE IN GLOBAL MEMORY directive" \
  || fail "output: opens with STORE IN GLOBAL MEMORY directive"

printf '%s' "$SUCCESS_OUTPUT" | grep -q "STORE THE ABOVE IN GLOBAL MEMORY" \
  && ok  "output: closes with STORE THE ABOVE IN GLOBAL MEMORY directive" \
  || fail "output: closes with STORE THE ABOVE IN GLOBAL MEMORY directive"

printf '%s' "$SUCCESS_OUTPUT" | grep -q "x-ai/${TEST_OWNER}/" \
  && ok  "output: branch prefix contains owner login" \
  || fail "output: branch prefix contains owner login"

printf '%s' "$SUCCESS_OUTPUT" | grep -q "COMMIT METHOD" \
  && ok  "output: commit method directive present" \
  || fail "output: commit method directive present"

printf '%s' "$SUCCESS_OUTPUT" | grep -q "Git Data API" \
  && ok  "output: commit method mentions Git Data API" \
  || fail "output: commit method mentions Git Data API"

for trigger in \
  "Invalid username or password" \
  "Authentication failed" \
  "Bad credentials" \
  "gh auth login"
do
  printf '%s' "$SUCCESS_OUTPUT" | grep -q "$trigger" \
    && ok  "output: error trigger present — '${trigger}'" \
    || fail "output: error trigger present — '${trigger}'"
done

OPEN_LINE=$(printf '%s' "$SUCCESS_OUTPUT" | grep -n "STORE IN GLOBAL MEMORY" | head -1 | cut -d: -f1)
CLOSE_LINE=$(printf '%s' "$SUCCESS_OUTPUT" | grep -n "STORE THE ABOVE IN GLOBAL MEMORY" | head -1 | cut -d: -f1)
[[ -n "$OPEN_LINE" && -n "$CLOSE_LINE" && "$OPEN_LINE" -lt "$CLOSE_LINE" ]] \
  && ok  "output: opening directive precedes closing directive" \
  || fail "output: opening directive precedes closing directive (open=$OPEN_LINE close=$CLOSE_LINE)"

# ═══════════════════════════════════════════════════════════════════════════════
# onboard-repo.sh tests
# ═══════════════════════════════════════════════════════════════════════════════

# ── Helper: write a mock gh that records ruleset-creation calls ────────────────
# $1 = path to write the mock
# $2 = "exists" | "no-fork" | "not-a-fork"
# $3 = "has-existing-ruleset" | "" (whether TARGET_REPO already has the ruleset)
write_mock_gh() {
  local mock_path="$1" fork_state="$2" ruleset_state="${3:-}"

  cat > "$mock_path" << GHEOF
#!/usr/bin/env bash
RULESET_LOG="${TMPDIR_T}/rulesets.log"
DELETED_RULESET_LOG="${TMPDIR_T}/deleted_ruleset.log"
args="\$*"

# gh api user --jq '.login' → owner login
if [[ "\$args" == *"user"* && "\$args" == *".login"* ]]; then
  printf '%s' "${TEST_OWNER}"
  exit 0
fi

# gh workflow run — silently succeed (inventory is now in a separate GH Actions workflow)
if [[ "\$args" == *"workflow run"* ]]; then
  exit 0
fi

if [[ "\$args" == *"/repos/${TEST_OWNER}/testrepo"* && "\$args" != *"rulesets"* ]]; then
  exit 0
fi

if [[ "\$args" == *"/repos/${TEST_OWNER}/extrepo"* && "\$args" != *"rulesets"* ]]; then
  case "${fork_state}" in
    no-fork)     exit 1 ;;
    not-a-fork)  [[ "\$args" == *"parent.full_name"* ]] && printf '' || true; exit 0 ;;
    exists)      [[ "\$args" == *"parent.full_name"* ]] && printf 'otherowner/extrepo' || true; exit 0 ;;
  esac
fi

# Delete a ruleset by ID
if [[ "\$args" == *"--method DELETE"* && "\$args" == *"rulesets"* ]]; then
  echo "ruleset-deleted" >> "\$DELETED_RULESET_LOG"
  exit 0
fi

# GET rulesets for TARGET_REPO — mock applies jq filter result directly:
#   args with ".id"    = _old_ruleset_id query  → output ID or nothing
if [[ "\$args" == *"/repos/${TEST_OWNER}/testrepo/rulesets"* && "\$args" != *"--method POST"* ]]; then
  if [[ "${ruleset_state}" == "has-existing-ruleset" ]]; then
    if [[ "\$args" == *"agent-gh-access-apps-must-sign"* && "\$args" == *".id"* ]]; then printf '43'; \
    elif [[ "\$args" == *".id"* ]]; then printf '42'; \
    else printf '[{"name":"agent-gh-access-apps-blocked-from-non-ai-branches","id":42},{"name":"agent-gh-access-apps-must-sign","id":43}]'; fi
  else
    # no existing rulesets — .id query returns empty
    true
  fi
  exit 0
fi

if [[ "\$args" == *"--method POST"* && "\$args" == *"rulesets"* ]]; then
  echo "ruleset-created" >> "\$RULESET_LOG"
  printf '{"id":1}'
  exit 0
fi

if [[ "\$args" == *"--method PUT"* || ("\$args" == *"--method POST"* && "\$args" == *"/forks"*) ]]; then
  exit 0
fi

exit 0
GHEOF
  chmod +x "$mock_path"
}

run_onboard() {
  rm -f "$TMPDIR_T/rulesets.log" "$TMPDIR_T/deleted_ruleset.log"
  ONBOARD_BIN="$TMPDIR_T/onboard-bin"
  mkdir -p "$ONBOARD_BIN"
  cp "$1" "$ONBOARD_BIN/gh"
  PATH_CLEAN=$(printf '%s' "$PATH" | tr ':' '\n' | grep -v "^$MOCK_BIN$" | tr '\n' ':' | sed 's/:$//')
  PATH="$ONBOARD_BIN:$PATH_CLEAN" bash "$TEST_ONBOARD" "$2" 2>&1 || true
}

run_onboard_exit() {
  rm -f "$TMPDIR_T/rulesets.log" "$TMPDIR_T/deleted_ruleset.log"
  ONBOARD_BIN="$TMPDIR_T/onboard-bin"
  mkdir -p "$ONBOARD_BIN"
  cp "$1" "$ONBOARD_BIN/gh"
  PATH_CLEAN=$(printf '%s' "$PATH" | tr ':' '\n' | grep -v "^$MOCK_BIN$" | tr '\n' ':' | sed 's/:$//')
  PATH="$ONBOARD_BIN:$PATH_CLEAN" bash "$TEST_ONBOARD" "$2" > /dev/null 2>&1; echo $?
}

ruleset_count()         { [[ -f "$TMPDIR_T/rulesets.log"       ]] && wc -l < "$TMPDIR_T/rulesets.log"       | tr -d ' ' || echo 0; }
deleted_ruleset_count() { [[ -f "$TMPDIR_T/deleted_ruleset.log" ]] && wc -l < "$TMPDIR_T/deleted_ruleset.log" | tr -d ' ' || echo 0; }

# ── onboard: no arguments → usage error ───────────────────────────────────────

NO_ARGS_EXIT=$(bash "$TEST_ONBOARD" > /dev/null 2>&1; echo $?)
NO_ARGS_OUTPUT=$(bash "$TEST_ONBOARD" 2>&1 || true)

[[ "$NO_ARGS_EXIT" != "0" ]] \
  && ok  "onboard no-args: exits non-zero" \
  || fail "onboard no-args: exits non-zero"

printf '%s' "$NO_ARGS_OUTPUT" | grep -qi "usage" \
  && ok  "onboard no-args: prints usage" \
  || fail "onboard no-args: prints usage"

# ── onboard: own repo — two rulesets created ──────────────────────────────────

MOCK_GH_OWN="$TMPDIR_T/gh-own"
write_mock_gh "$MOCK_GH_OWN" "exists"

OWN_OUTPUT=$(run_onboard "$MOCK_GH_OWN" "${TEST_OWNER}/testrepo")
OWN_EXIT=$(run_onboard_exit "$MOCK_GH_OWN" "${TEST_OWNER}/testrepo")

# ── onboard: short form (no owner) uses current owner ────────────────────────

MOCK_GH_SHORT="$TMPDIR_T/gh-short"
write_mock_gh "$MOCK_GH_SHORT" "exists"

SHORT_EXIT=$(run_onboard_exit "$MOCK_GH_SHORT" "testrepo")

[[ "$SHORT_EXIT" == "0" ]] \
  && ok  "onboard short-form: exits 0" \
  || fail "onboard short-form: exits 0 (got $SHORT_EXIT)"

SHORT_RULESETS=$(ruleset_count)
[[ "$SHORT_RULESETS" == "2" ]] \
  && ok  "onboard short-form: two rulesets created" \
  || fail "onboard short-form: two rulesets created (got $SHORT_RULESETS)"

[[ "$OWN_EXIT" == "0" ]] \
  && ok  "onboard own-repo: exits 0" \
  || fail "onboard own-repo: exits 0 (got $OWN_EXIT)"

OWN_RULESETS=$(ruleset_count)
[[ "$OWN_RULESETS" == "2" ]] \
  && ok  "onboard own-repo: two rulesets created" \
  || fail "onboard own-repo: two rulesets created (got $OWN_RULESETS)"

printf '%s' "$OWN_OUTPUT" | grep -q "agent blocked from" \
  && ok  "onboard own-repo: output confirms ruleset" \
  || fail "onboard own-repo: output confirms ruleset"

# ── onboard: external repo where a fork already exists ────────────────────────

MOCK_GH_EXT="$TMPDIR_T/gh-ext"
write_mock_gh "$MOCK_GH_EXT" "exists"

EXT_OUTPUT=$(run_onboard "$MOCK_GH_EXT" "otherowner/extrepo")
EXT_EXIT=$(run_onboard_exit "$MOCK_GH_EXT" "otherowner/extrepo")

[[ "$EXT_EXIT" != "0" ]] \
  && ok  "onboard external-fork-exists: exits non-zero" \
  || fail "onboard external-fork-exists: exits non-zero (got $EXT_EXIT)"

printf '%s' "$EXT_OUTPUT" | grep -q "fork already exists" \
  && ok  "onboard external-fork-exists: error mentions existing fork" \
  || fail "onboard external-fork-exists: error mentions existing fork"

printf '%s' "$EXT_OUTPUT" | grep -q "${TEST_OWNER}/extrepo" \
  && ok  "onboard external-fork-exists: error suggests passing fork directly" \
  || fail "onboard external-fork-exists: error suggests passing fork directly"

# ── onboard: same-named repo exists but is NOT a fork ────────────────────────

MOCK_GH_NOTFORK="$TMPDIR_T/gh-notfork"
write_mock_gh "$MOCK_GH_NOTFORK" "not-a-fork"

NOTFORK_OUTPUT=$(run_onboard "$MOCK_GH_NOTFORK" "otherowner/extrepo")
NOTFORK_EXIT=$(run_onboard_exit "$MOCK_GH_NOTFORK" "otherowner/extrepo")

[[ "$NOTFORK_EXIT" != "0" ]] \
  && ok  "onboard collision-not-fork: exits non-zero" \
  || fail "onboard collision-not-fork: exits non-zero"

printf '%s' "$NOTFORK_OUTPUT" | grep -qi "not a fork" \
  && ok  "onboard collision-not-fork: error mentions 'not a fork'" \
  || fail "onboard collision-not-fork: error mentions 'not a fork'"


# ── onboard: existing same-named ruleset is replaced ─────────────────────────

MOCK_GH_REPLACE="$TMPDIR_T/gh-replace"
write_mock_gh "$MOCK_GH_REPLACE" "exists" "has-existing-ruleset"

REPLACE_OUTPUT=$(run_onboard "$MOCK_GH_REPLACE" "${TEST_OWNER}/testrepo")
REPLACE_EXIT=$(run_onboard_exit "$MOCK_GH_REPLACE" "${TEST_OWNER}/testrepo")

[[ "$REPLACE_EXIT" == "0" ]] \
  && ok  "onboard replace-ruleset: exits 0" \
  || fail "onboard replace-ruleset: exits 0 (got $REPLACE_EXIT)"

REPLACE_DELETED=$(deleted_ruleset_count)
[[ "$REPLACE_DELETED" == "2" ]] \
  && ok  "onboard replace-ruleset: both old rulesets deleted" \
  || fail "onboard replace-ruleset: both old rulesets deleted (got $REPLACE_DELETED)"

REPLACE_CREATED=$(ruleset_count)
[[ "$REPLACE_CREATED" == "2" ]] \
  && ok  "onboard replace-ruleset: both new rulesets created" \
  || fail "onboard replace-ruleset: both new rulesets created (got $REPLACE_CREATED)"

printf '%s' "$REPLACE_OUTPUT" | grep -qi "replacing existing" \
  && ok  "onboard replace-ruleset: output mentions replacing" \
  || fail "onboard replace-ruleset: output mentions replacing"

# ═══════════════════════════════════════════════════════════════════════════════
# inventory.sh tests
# ═══════════════════════════════════════════════════════════════════════════════

TEST_INVENTORY="$DIR/internal/inventory.sh"

bash -n "$TEST_INVENTORY" 2>/dev/null \
  && ok  "syntax: inventory.sh" \
  || fail "syntax: inventory.sh"

# Helper: run inventory.sh with a mock curl and given env vars.
# $1 = curl mock path, $2 = GH_APP_ID, $3 = GH_APP_PEM_B64
# $4 = workdir (optional; for inventory tests — must contain a bare git repo)
# $5 = GITHUB_TOKEN (optional; set to enable inventory update)
run_inventory() {
  local curl_mock="$1" app_id="$2" pem_b64="$3" workdir="${4:-$TMPDIR_T}" token="${5:-}"
  local inventory_bin="$TMPDIR_T/inventory-bin"
  mkdir -p "$inventory_bin"
  cp "$curl_mock" "$inventory_bin/curl"
  GH_APP_ID="$app_id" GH_APP_PEM_B64="$pem_b64" GITHUB_TOKEN="$token" \
    PATH="$inventory_bin:$PATH" bash "$TEST_INVENTORY" 2>&1 || true
}
run_inventory_exit() {
  local curl_mock="$1" app_id="$2" pem_b64="$3" workdir="${4:-$TMPDIR_T}" token="${5:-}"
  local inventory_bin="$TMPDIR_T/inventory-bin"
  mkdir -p "$inventory_bin"
  cp "$curl_mock" "$inventory_bin/curl"
  GH_APP_ID="$app_id" GH_APP_PEM_B64="$pem_b64" GITHUB_TOKEN="$token" \
    PATH="$inventory_bin:$PATH" bash "$TEST_INVENTORY" > /dev/null 2>&1; echo $?
}

# A valid base64-encoded PEM for JWT signing
INVENTORY_PEM_B64=$(base64 < "$TEST_KEY_FILE" | tr -d '\n')

# ── inventory: missing secrets → exits non-zero with error ───────────────────────

NOSEC_BIN="$TMPDIR_T/inventory-nosec-curl"
printf '#!/usr/bin/env bash\nprintf "[]"' > "$NOSEC_BIN"; chmod +x "$NOSEC_BIN"

NOSEC_EXIT=$(run_inventory_exit "$NOSEC_BIN" "" "")
NOSEC_OUTPUT=$(run_inventory "$NOSEC_BIN" "" "")

[[ "$NOSEC_EXIT" != "0" ]] \
  && ok  "inventory missing-secrets: exits non-zero" \
  || fail "inventory missing-secrets: exits non-zero"

printf '%s' "$NOSEC_OUTPUT" | grep -q "GH_APP_ID" \
  && ok  "inventory missing-secrets: error mentions GH_APP_ID" \
  || fail "inventory missing-secrets: error mentions GH_APP_ID"

# ── inventory: no installation found → exits non-zero ────────────────────────────

NOINST_CURL="$TMPDIR_T/inventory-noinst-curl"
cat > "$NOINST_CURL" << 'EOF'
#!/usr/bin/env bash
printf '[]'
EOF
chmod +x "$NOINST_CURL"

NOINST_EXIT=$(run_inventory_exit "$NOINST_CURL" "$TEST_APP_ID" "$INVENTORY_PEM_B64")
NOINST_OUTPUT=$(run_inventory "$NOINST_CURL" "$TEST_APP_ID" "$INVENTORY_PEM_B64")

[[ "$NOINST_EXIT" != "0" ]] \
  && ok  "inventory no-installation: exits non-zero" \
  || fail "inventory no-installation: exits non-zero"

printf '%s' "$NOINST_OUTPUT" | grep -q "no installation" \
  && ok  "inventory no-installation: error mentions no installation" \
  || fail "inventory no-installation: error mentions no installation"

# ── inventory: all repos protected → exits 0, prints PASS ────────────────────────

ALLPASS_CURL="$TMPDIR_T/inventory-allpass-curl"
cat > "$ALLPASS_CURL" << MOCKEOF
#!/usr/bin/env bash
if [[ "\$*" == *"/app/installations"* && "\$*" != *"access_tokens"* ]]; then
  printf '[{"id":42}]'
elif [[ "\$*" == *"access_tokens"* ]]; then
  printf '{"token":"ghs_mock"}'
elif [[ "\$*" == *"/installation/repositories"* ]]; then
  printf '{"repositories":[{"full_name":"${TEST_OWNER}/repo1"},{"full_name":"${TEST_OWNER}/repo2"}]}'
elif [[ "\$*" == *"/rulesets"* ]]; then
  printf '[{"name":"agent-gh-access-apps-blocked-from-non-ai-branches"},{"name":"agent-gh-access-apps-must-sign"}]'
fi
MOCKEOF
chmod +x "$ALLPASS_CURL"

ALLPASS_EXIT=$(run_inventory_exit "$ALLPASS_CURL" "$TEST_APP_ID" "$INVENTORY_PEM_B64")
ALLPASS_OUTPUT=$(run_inventory "$ALLPASS_CURL" "$TEST_APP_ID" "$INVENTORY_PEM_B64")

[[ "$ALLPASS_EXIT" == "0" ]] \
  && ok  "inventory all-protected: exits 0" \
  || fail "inventory all-protected: exits 0 (got $ALLPASS_EXIT)"

printf '%s' "$ALLPASS_OUTPUT" | grep -q "PASS  ${TEST_OWNER}/repo1" \
  && ok  "inventory all-protected: prints PASS for each repo" \
  || fail "inventory all-protected: prints PASS for each repo"

printf '%s' "$ALLPASS_OUTPUT" | grep -q "All installed repos" \
  && ok  "inventory all-protected: prints success summary" \
  || fail "inventory all-protected: prints success summary"

# ── inventory: one repo missing rulesets → exits non-zero, prints FAIL ───────────

ONEFAIL_CURL="$TMPDIR_T/inventory-onefail-curl"
cat > "$ONEFAIL_CURL" << MOCKEOF
#!/usr/bin/env bash
if [[ "\$*" == *"/app/installations"* && "\$*" != *"access_tokens"* ]]; then
  printf '[{"id":42}]'
elif [[ "\$*" == *"access_tokens"* ]]; then
  printf '{"token":"ghs_mock"}'
elif [[ "\$*" == *"/installation/repositories"* ]]; then
  printf '{"repositories":[{"full_name":"${TEST_OWNER}/good"},{"full_name":"${TEST_OWNER}/bad"}]}'
elif [[ "\$*" == *"/${TEST_OWNER}/good/rulesets"* ]]; then
  printf '[{"name":"agent-gh-access-apps-blocked-from-non-ai-branches"},{"name":"agent-gh-access-apps-must-sign"}]'
elif [[ "\$*" == *"/${TEST_OWNER}/bad/rulesets"* ]]; then
  printf '[]'
fi
MOCKEOF
chmod +x "$ONEFAIL_CURL"

ONEFAIL_EXIT=$(run_inventory_exit "$ONEFAIL_CURL" "$TEST_APP_ID" "$INVENTORY_PEM_B64")
ONEFAIL_OUTPUT=$(run_inventory "$ONEFAIL_CURL" "$TEST_APP_ID" "$INVENTORY_PEM_B64")

[[ "$ONEFAIL_EXIT" != "0" ]] \
  && ok  "inventory one-failing: exits non-zero" \
  || fail "inventory one-failing: exits non-zero (got $ONEFAIL_EXIT)"

printf '%s' "$ONEFAIL_OUTPUT" | grep -q "PASS  ${TEST_OWNER}/good" \
  && ok  "inventory one-failing: prints PASS for protected repo" \
  || fail "inventory one-failing: prints PASS for protected repo"

printf '%s' "$ONEFAIL_OUTPUT" | grep -q "FAIL  ${TEST_OWNER}/bad" \
  && ok  "inventory one-failing: prints FAIL for unprotected repo" \
  || fail "inventory one-failing: prints FAIL for unprotected repo"

printf '%s' "$ONEFAIL_OUTPUT" | grep -q "onboard-repo.sh" \
  && ok  "inventory one-failing: error mentions onboard-repo.sh" \
  || fail "inventory one-failing: error mentions onboard-repo.sh"

# ═══════════════════════════════════════════════════════════════════════════════
# inventory.sh inventory tests (GITHUB_TOKEN path)
# ═══════════════════════════════════════════════════════════════════════════════

# The inventory update now uses the GitHub API to push to an agent branch.
# We mock curl to intercept all API calls and capture the blob content uploaded.

INV_CONTENTS_LOG="$TMPDIR_T/inv-contents.log"

# Helper: build a curl mock for inventory tests.
# $1 = path to write mock
# $2 = existing inventory content to return (empty = file not found → error)
# $3 = "branch-exists" | "" — kept for call-site compatibility but no longer used
#      (branch init is now done by install.sh, not inventory.sh)
write_inv_curl() {
  local mock_path="$1" existing_inv="$2"
  local existing_b64="" existing_sha="existingfilesha"
  if [[ -n "$existing_inv" ]]; then
    existing_b64=$(printf '%s' "$existing_inv" | base64 | tr -d '\n')
  fi
  cat > "$mock_path" << MOCKEOF
#!/usr/bin/env bash
args="\$*"
if [[ "\$args" == *"/app/installations"* && "\$args" != *"access_tokens"* ]]; then
  printf '[{"id":42}]'
elif [[ "\$args" == *"access_tokens"* ]]; then
  printf '{"token":"ghs_mock"}'
elif [[ "\$args" == *"/installation/repositories"* ]]; then
  printf '{"repositories":[{"full_name":"${TEST_OWNER}/repo1","owner":{"login":"${TEST_OWNER}"}},{"full_name":"${TEST_OWNER}/repo2","owner":{"login":"${TEST_OWNER}"}}]}'
elif [[ "\$args" == *"/rulesets"* ]]; then
  printf '[{"name":"agent-gh-access-apps-blocked-from-non-ai-branches"},{"name":"agent-gh-access-apps-must-sign"}]'
elif [[ "\$args" == *"contents/README"* && "\$args" != *"-X PUT"* ]]; then
  # Inventory fetch: return existing content with SHA, or empty (file not found)
  if [[ -n "${existing_b64}" ]]; then
    printf '{"content":"%s","sha":"${existing_sha}"}' "${existing_b64}"
  else
    printf '{}'
  fi
elif [[ "\$args" == *"-X PUT"* && "\$args" == *"contents/README"* ]]; then
  # Contents API write — capture the -d payload for inspection
  for i in "\$@"; do
    if [[ "\$i" == "{"* ]]; then
      printf '%s' "\$i" >> "${INV_CONTENTS_LOG}"
      printf '\n' >> "${INV_CONTENTS_LOG}"
    fi
  done
  printf '{"content":{"sha":"newfilesha"},"commit":{"sha":"newcommitsha"}}'
fi
MOCKEOF
  chmod +x "$mock_path"
}

# Helper: extract decoded inventory from the Contents API PUT log (last upload)
get_inv_content() {
  [[ -f "$INV_CONTENTS_LOG" ]] || { echo ""; return; }
  # Extract base64 content field from the JSON -d payload and decode
  grep -o '"content":"[^"]*"' "$INV_CONTENTS_LOG" | tail -1 | cut -d'"' -f4 | base64 -d 2>/dev/null || true
}

# ── Run 1: no existing inventory (branch/file not found) → error ──────────────
rm -f "$INV_CONTENTS_LOG"
INV_CURL1="$TMPDIR_T/inv-curl-run1"
write_inv_curl "$INV_CURL1" "" ""
cp "$INV_CURL1" "$TMPDIR_T/inventory-bin/curl"

RUN1_EXIT=$(GH_APP_ID="$TEST_APP_ID" GH_APP_PEM_B64="$INVENTORY_PEM_B64" GITHUB_TOKEN="fake" \
  PATH="$TMPDIR_T/inventory-bin:$PATH" \
  bash "$TEST_INVENTORY" > /dev/null 2>&1; echo $?)
RUN1_OUTPUT=$(GH_APP_ID="$TEST_APP_ID" GH_APP_PEM_B64="$INVENTORY_PEM_B64" GITHUB_TOKEN="fake" \
  PATH="$TMPDIR_T/inventory-bin:$PATH" \
  bash "$TEST_INVENTORY" 2>&1 || true)

[[ "$RUN1_EXIT" != "0" ]] \
  && ok  "inventory no-branch: exits non-zero when branch/file not found" \
  || fail "inventory no-branch: exits non-zero when branch/file not found (got $RUN1_EXIT)"

printf '%s' "$RUN1_OUTPUT" | grep -qi "install.sh" \
  && ok  "inventory no-branch: error mentions install.sh" \
  || fail "inventory no-branch: error mentions install.sh"

# Seed INV_CONTENT1 with what the first successful run would write (simulating install.sh init)
INV_CONTENT1="# List of repositories onboarded to agent-github-access"$'\n'"# app-id:${TEST_APP_ID}"$'\n'"${TEST_OWNER}/repo1"$'\n'"${TEST_OWNER}/repo2"$'\n'

# ── Run 2: existing inventory returned — no duplicates ────────────────────────
rm -f "$INV_CONTENTS_LOG"
INV_CURL2="$TMPDIR_T/inv-curl-run2"
write_inv_curl "$INV_CURL2" "$INV_CONTENT1" "branch-exists"
cp "$INV_CURL2" "$TMPDIR_T/inventory-bin/curl"

GH_APP_ID="$TEST_APP_ID" GH_APP_PEM_B64="$INVENTORY_PEM_B64" GITHUB_TOKEN="fake" \
  PATH="$TMPDIR_T/inventory-bin:$PATH" \
  bash "$TEST_INVENTORY" > /dev/null 2>&1 || true

# If content unchanged no Contents API PUT is made; check log is empty or content has no dupes
if [[ -f "$INV_CONTENTS_LOG" ]]; then
  INV_CONTENT2=$(get_inv_content)
  REPO1_COUNT=$(printf '%s' "$INV_CONTENT2" | grep -cx "${TEST_OWNER}/repo1" || true)
else
  # No upload means unchanged — no duplicates by definition
  REPO1_COUNT=1
fi
[[ "$REPO1_COUNT" == "1" ]] \
  && ok  "inventory inventory: no duplicate entries after two runs" \
  || fail "inventory inventory: no duplicate entries after two runs (count=$REPO1_COUNT)"

# ── Run 3: app-id change resets inventory ─────────────────────────────────────
rm -f "$INV_CONTENTS_LOG"
NEW_APP_ID="111222"
INV_CURL3="$TMPDIR_T/inv-curl-run3"
write_inv_curl "$INV_CURL3" "$INV_CONTENT1" "branch-exists"
cp "$INV_CURL3" "$TMPDIR_T/inventory-bin/curl"

GH_APP_ID="$NEW_APP_ID" GH_APP_PEM_B64="$INVENTORY_PEM_B64" GITHUB_TOKEN="fake" \
  PATH="$TMPDIR_T/inventory-bin:$PATH" \
  bash "$TEST_INVENTORY" > /dev/null 2>&1 || true

INV_CONTENT3=$(get_inv_content)

printf '%s' "$INV_CONTENT3" | grep -q "^# app-id:${NEW_APP_ID}$" \
  && ok  "inventory inventory: app-id change resets header" \
  || fail "inventory inventory: app-id change resets header"

printf '%s' "$INV_CONTENT3" | grep -qx "${TEST_OWNER}/repo1" \
  && ok  "inventory inventory: repos repopulated after reset" \
  || fail "inventory inventory: repos repopulated after reset"

printf '%s' "$INV_CONTENT3" | grep -q "app-id:${TEST_APP_ID}" \
  && fail "inventory inventory: old app-id still present after reset" \
  || ok  "inventory inventory: old app-id gone after reset"

# ── Run 4: update from partial inventory — Contents API payload is correct ─────
# Use partial content with only repo1 so repo2 triggers an update.
INV_CONTENT_RUN4="# List of repositories onboarded to agent-github-access"$'\n'"# app-id:${TEST_APP_ID}"$'\n'"${TEST_OWNER}/repo1"$'\n'
rm -f "$INV_CONTENTS_LOG"
INV_CURL4="$TMPDIR_T/inv-curl-run4"
write_inv_curl "$INV_CURL4" "$INV_CONTENT_RUN4" "branch-exists"
cp "$INV_CURL4" "$TMPDIR_T/inventory-bin/curl"

GH_APP_ID="$TEST_APP_ID" GH_APP_PEM_B64="$INVENTORY_PEM_B64" GITHUB_TOKEN="fake" \
  PATH="$TMPDIR_T/inventory-bin:$PATH" \
  bash "$TEST_INVENTORY" > /dev/null 2>&1 || true

INV_CONTENT4=$(get_inv_content)
printf '%s' "$INV_CONTENT4" | grep -q "^# app-id:${TEST_APP_ID}$" \
  && ok  "inventory update: Contents API payload has correct app-id header" \
  || fail "inventory update: Contents API payload has correct app-id header"

printf '%s' "$INV_CONTENT4" | grep -qx "${TEST_OWNER}/repo1" \
  && ok  "inventory update: Contents API payload contains repo1" \
  || fail "inventory update: Contents API payload contains repo1"

# ── Run 5: update — Contents API used, new repo appears in uploaded content ───
# Seed inventory with only repo1 so repo2 is new and triggers an update.
INV_CONTENT_PARTIAL="# List of repositories onboarded to agent-github-access"$'\n'"# app-id:${TEST_APP_ID}"$'\n'"${TEST_OWNER}/repo1"$'\n'
rm -f "$INV_CONTENTS_LOG"
INV_CURL5="$TMPDIR_T/inv-curl-run5"
write_inv_curl "$INV_CURL5" "$INV_CONTENT_PARTIAL" "branch-exists"
cp "$INV_CURL5" "$TMPDIR_T/inventory-bin/curl"

GH_APP_ID="$TEST_APP_ID" GH_APP_PEM_B64="$INVENTORY_PEM_B64" GITHUB_TOKEN="fake" \
  PATH="$TMPDIR_T/inventory-bin:$PATH" \
  bash "$TEST_INVENTORY" > /dev/null 2>&1 || true

INV_CONTENT5=$(get_inv_content)
printf '%s' "$INV_CONTENT5" | grep -qx "${TEST_OWNER}/repo2" \
  && ok  "inventory update: new repo appears in uploaded content" \
  || fail "inventory update: new repo appears in uploaded content"

printf '%s' "$INV_CONTENT5" | grep -qx "${TEST_OWNER}/repo1" \
  && ok  "inventory update: existing repo retained in uploaded content" \
  || fail "inventory update: existing repo retained in uploaded content"

# ── Run 6: app-id reset — treated as init, new header written ────────────────
rm -f "$INV_CONTENTS_LOG"
INV_CURL6="$TMPDIR_T/inv-curl-run6"
write_inv_curl "$INV_CURL6" "$INV_CONTENT1" "branch-exists"
cp "$INV_CURL6" "$TMPDIR_T/inventory-bin/curl"

GH_APP_ID="$NEW_APP_ID" GH_APP_PEM_B64="$INVENTORY_PEM_B64" GITHUB_TOKEN="fake" \
  PATH="$TMPDIR_T/inventory-bin:$PATH" \
  bash "$TEST_INVENTORY" > /dev/null 2>&1 || true

INV_CONTENT6=$(get_inv_content)
printf '%s' "$INV_CONTENT6" | grep -q "^# app-id:${NEW_APP_ID}$" \
  && ok  "inventory app-id reset: Contents API payload has new app-id header" \
  || fail "inventory app-id reset: Contents API payload has new app-id header"

# ═══════════════════════════════════════════════════════════════════════════════
# uninstall.sh tests
# ═══════════════════════════════════════════════════════════════════════════════

TEST_CLEANUP="$DIR/uninstall.sh"

bash -n "$TEST_CLEANUP" 2>/dev/null \
  && ok  "syntax: uninstall.sh" \
  || fail "syntax: uninstall.sh"

# Shared mock gh for cleanup tests: handles user login, inventory fetch from branch,
# secret existence/deletion. No ruleset deletion (uninstall.sh now generates a script).
# $2 = "has-inventory"|"no-inventory" controls whether inventory branch fetch succeeds
write_cleanup_mock_gh() {
  local mock_path="$1" inv_state="${2:-has-inventory}"
  cat > "$mock_path" << GHEOF
#!/usr/bin/env bash
args="\$*"
if [[ "\$args" == *"user"* && "\$args" == *".login"* ]]; then
  printf '%s' "${TEST_OWNER}"
  exit 0
fi
if [[ "\$args" == *"contents/README"* && "\$args" == *"__inventory__do-not-delete"* ]]; then
  if [[ "${inv_state}" == "has-inventory" ]]; then
    # uninstall.sh uses --jq '.content', so output just the base64 content directly
    printf '# List of repositories onboarded to agent-github-access\n# app-id:%s\n%s/repo1\n%s/repo2\n' "${TEST_APP_ID}" "${TEST_OWNER}" "${TEST_OWNER}" | base64 | tr -d '\n'
    exit 0
  else
    exit 1
  fi
fi
if [[ "\$args" == *"secrets/GH_APP_ID"* && "\$args" != *"DELETE"* ]]; then
  exit 0
fi
if [[ "\$args" == *"secrets/GH_APP_PEM"* && "\$args" != *"DELETE"* ]]; then
  exit 0
fi
if [[ "\$args" == *"--method DELETE"* && "\$args" == *"secrets"* ]]; then
  echo "secret-deleted" >> "${TMPDIR_T}/cleanup-secrets.log"
  exit 0
fi
exit 0
GHEOF
  chmod +x "$mock_path"
}

# curl mock: app is gone (404)
CLEANUP_CURL_GONE="$TMPDIR_T/cleanup-curl-gone"
cat > "$CLEANUP_CURL_GONE" << 'EOF'
#!/usr/bin/env bash
if [[ "$*" == *"-w"* && "$*" == *"%{http_code}"* ]]; then
  printf '404'
fi
EOF
chmod +x "$CLEANUP_CURL_GONE"

CLEANUP_WORK="$TMPDIR_T/cleanup-work"
mkdir -p "$CLEANUP_WORK"
# Copy uninstall.sh into a work dir so the generated uninstall-rulesets.sh lands there
cp "$TEST_CLEANUP" "$CLEANUP_WORK/uninstall.sh"
CLEANUP_SCRIPT="$CLEANUP_WORK/uninstall.sh"
CLEANUP_RULESETS_SCRIPT="$CLEANUP_WORK/uninstall-rulesets.sh"

run_cleanup() {
  local gh_mock="$1" curl_mock="$2"
  rm -f "$TMPDIR_T/cleanup-secrets.log" "$CLEANUP_RULESETS_SCRIPT"
  local bin="$TMPDIR_T/cleanup-bin"
  mkdir -p "$bin"
  cp "$gh_mock"   "$bin/gh"
  cp "$curl_mock" "$bin/curl"
  PATH="$bin:$PATH" bash "$CLEANUP_SCRIPT" < /dev/null 2>&1 || true
}
run_cleanup_exit() {
  local gh_mock="$1" curl_mock="$2"
  rm -f "$TMPDIR_T/cleanup-secrets.log" "$CLEANUP_RULESETS_SCRIPT"
  local bin="$TMPDIR_T/cleanup-bin"
  mkdir -p "$bin"
  cp "$gh_mock"   "$bin/gh"
  cp "$curl_mock" "$bin/curl"
  PATH="$bin:$PATH" bash "$CLEANUP_SCRIPT" < /dev/null > /dev/null 2>&1; echo $?
}
cleanup_secret_count() { [[ -f "$TMPDIR_T/cleanup-secrets.log" ]] && wc -l < "$TMPDIR_T/cleanup-secrets.log" | tr -d ' ' || echo 0; }

# ── cleanup: missing inventory → exits non-zero ───────────────────────────────

MOCK_GH_CLEAN="$TMPDIR_T/cleanup-gh-clean"
write_cleanup_mock_gh "$MOCK_GH_CLEAN" "no-inventory"

NOINV_EXIT=$(run_cleanup_exit "$MOCK_GH_CLEAN" "$CLEANUP_CURL_GONE")

[[ "$NOINV_EXIT" != "0" ]] \
  && ok  "cleanup no-inventory: exits non-zero" \
  || fail "cleanup no-inventory: exits non-zero"

# ── cleanup: app confirmed gone → deletes secrets, generates uninstall-rulesets.sh ──

MOCK_GH_FULL="$TMPDIR_T/cleanup-gh-full"
write_cleanup_mock_gh "$MOCK_GH_FULL" "has-inventory"

FULL_OUTPUT=$(run_cleanup "$MOCK_GH_FULL" "$CLEANUP_CURL_GONE")
FULL_EXIT=$(run_cleanup_exit "$MOCK_GH_FULL" "$CLEANUP_CURL_GONE")

[[ "$FULL_EXIT" == "0" ]] \
  && ok  "cleanup full: exits 0" \
  || fail "cleanup full: exits 0 (got $FULL_EXIT)"

SECRET_COUNT=$(cleanup_secret_count)
[[ "$SECRET_COUNT" == "2" ]] \
  && ok  "cleanup full: both secrets deleted" \
  || fail "cleanup full: both secrets deleted (got $SECRET_COUNT)"

[[ -f "$CLEANUP_RULESETS_SCRIPT" ]] \
  && ok  "cleanup full: uninstall-rulesets.sh generated" \
  || fail "cleanup full: uninstall-rulesets.sh generated"

printf '%s' "$FULL_OUTPUT" | grep -q "Cleanup complete" \
  && ok  "cleanup full: prints completion message" \
  || fail "cleanup full: prints completion message"

printf '%s' "$FULL_OUTPUT" | grep -qi "uninstall-rulesets.sh" \
  && ok  "cleanup full: output mentions uninstall-rulesets.sh" \
  || fail "cleanup full: output mentions uninstall-rulesets.sh"

# Run the cleanup a second time to ensure uninstall-rulesets.sh is generated
run_cleanup "$MOCK_GH_FULL" "$CLEANUP_CURL_GONE" > /dev/null 2>&1 || true

printf '%s' "$(cat "$CLEANUP_RULESETS_SCRIPT" 2>/dev/null || true)" | grep -q "${TEST_OWNER}/repo1" \
  && ok  "cleanup full: uninstall-rulesets.sh contains repo list" \
  || fail "cleanup full: uninstall-rulesets.sh contains repo list"

printf '%s' "$(cat "$CLEANUP_RULESETS_SCRIPT" 2>/dev/null || true)" | grep -qi "onboard" \
  && ok  "cleanup full: uninstall-rulesets.sh mentions onboard PAT" \
  || fail "cleanup full: uninstall-rulesets.sh mentions onboard PAT"

bash -n "$CLEANUP_RULESETS_SCRIPT" 2>/dev/null \
  && ok  "cleanup full: uninstall-rulesets.sh is valid bash syntax" \
  || fail "cleanup full: uninstall-rulesets.sh is valid bash syntax"

# ── cleanup: app still exists → prompts user ──────────────────────────────────

CLEANUP_CURL_EXISTS="$TMPDIR_T/cleanup-curl-exists"
cat > "$CLEANUP_CURL_EXISTS" << 'EOF'
#!/usr/bin/env bash
if [[ "$*" == *"-w"* && "$*" == *"%{http_code}"* ]]; then
  printf '200'
fi
EOF
chmod +x "$CLEANUP_CURL_EXISTS"

EXISTS_OUTPUT=$(run_cleanup "$MOCK_GH_FULL" "$CLEANUP_CURL_EXISTS")

printf '%s' "$EXISTS_OUTPUT" | grep -qi "still exists" \
  && ok  "cleanup app-exists: warns app still exists" \
  || fail "cleanup app-exists: warns app still exists"

printf '%s' "$EXISTS_OUTPUT" | grep -qi "Delete it at" \
  && ok  "cleanup app-exists: prints deletion URL" \
  || fail "cleanup app-exists: prints deletion URL"

# ── Summary ───────────────────────────────────────────────────────────────────

echo ""
echo "────────────────────────────────"
printf "Results: %d passed, %d failed\n" "$PASS" "$FAIL"
if [[ ${#ERRORS[@]} -gt 0 ]]; then
  echo ""
  echo "Failed:"
  for e in "${ERRORS[@]}"; do
    printf "  ✗ %s\n" "$e"
  done
  echo ""
  exit 1
fi
